### ISSUE TITLE
歌词显示

### ISSUE THREAD

**Issue by listen1** [listen1/listen1_chrome_extension#10]

**Comment by listen1** [comment]
solved https://github.com/listen1/listen1_chrome_extension/commit/6bd309f6432c360bec6307d133e586fec001d254

**Comment by fanhojo** [comment]
歌词显示的位置好隐蔽啊，我下载了新版左翻右翻，愣是没找到哪里有歌词显示功能，结果无意间打开播放列表时才突然眼前一亮，好精致的歌词显示啊！是同步显示的！太棒了！
