### ISSUE TITLE
无法打开网易云页面的歌单

### ISSUE THREAD

**Issue by leihaha** [listen1/listen1_chrome_extension#100]
无法打开网易云页面的推荐歌单

**Comment by dianbanjiu** [comment]
我这几天也是，网易云歌单一直加载，一直无法进去

**Comment by Moobusy** [comment]
读了下代码，可能以前歌单里面的一个textarea里面存的明文json，现在改成加密了，需要作者来看看，我试着base64 decode 没有成功

**Comment by listen1** [comment]
已经合并，赞 @Moobusy
