### ISSUE TITLE
Edge插件，浏览器标签和底端播放/暂停图标是反的，强迫症有点难受

### ISSUE THREAD

**Issue by LuneZ** [listen1/listen1_chrome_extension#1049]
![image](https://user-images.githubusercontent.com/16446199/220811928-40bda3c1-099f-4cb1-a240-719eea76258b.png)
![image](https://user-images.githubusercontent.com/16446199/220811961-eb83ed93-5e6c-43bf-9416-77a10fb4f065.png)

**Comment by mikelxk** [comment]
#957 #956
