### ISSUE TITLE
当前歌曲仅能在酷我音乐手机端最新版播放

### ISSUE THREAD

**Issue by fandypeng** [listen1/listen1_chrome_extension#1054]
如题，酷我源的一些歌曲，偶尔会遇到这个语音提醒...

**Comment by zyp6666** [comment]
> 

是版权原因还是bug？

**Comment by adams-github** [comment]
昨天开始，酷我音源目前获取到的播放链接，偶尔就会这样提示（播放链接的长度11秒），估计是酷我平台做的改动，不是这个插件的问题

**Comment by bl-sun** [comment]
我也听到了“当前歌曲仅能在酷我音乐手机端最新版播放”

**Comment by adams-github** [comment]
酷我获取播放url的接口，我通过postman模拟请求，同样的请求参数，有50%的概率会返回播放连接结尾是“588957081.mp3”，就是提示“当前歌曲仅能在酷我音乐手机端最新版播放”

**Comment by lowa9** [comment]
怎么解决嘞

**Comment by zhangninggit** [comment]
周杰伦的几乎团灭

**Comment by kongyuzhuo** [comment]
我这几天也遇到了这个问题

**Comment by yuchen-login** [comment]
这算不算垄断啊  好像可以告了  真的烦人

**Comment by Mamong** [comment]
需要加什么请求头了吧

**Comment by HXY2023** [comment]
周董的歌全军覆没，怎么办/

**Comment by Akak1234567** [comment]
咋整

**Comment by weiwenzhao1** [comment]
同样

**Comment by symx23** [comment]
同上，有啥办法解决没

**Comment by YYDHZW** [comment]
听了一天<<当前歌曲仅能在酷我音乐手机端最新版播放>>了,救救我吧

**Comment by WANGZK0127** [comment]
有大佬有解决办法没

**Comment by NIGANSA** [comment]
求解决！！同样这个问题

**Comment by Mcdull0921** [comment]
前几天连续请求可以请求到一次正确的路径，现在无论请求多少次都只会返回588957081.mp3

> 酷我获取播放url的接口，我通过postman模拟请求，同样的请求参数，有50%的概率会返回播放连接结尾是“588957081.mp3”，就是提示“当前歌曲仅能在酷我音乐手机端最新版播放”

**Comment by bwxz** [comment]
哭了

**Comment by bwxz** [comment]
> 咋整

快点@Listen1  版主，快点给插件版本增加上播放本地歌曲功能

**Comment by RamPrime** [comment]
同求，或者看看怎么modify一下跳过这些11s的歌曲

**Comment by oychshy** [comment]
更换接口即可
https://github.com/QiuYaohong/kuwoMusicApi/issues/13#issue-1536738334

**Comment by listen1** [comment]
快速的解决方案是在设置中的自动切换源关闭，或者把切换源中把酷我的打钩取消。

已经有好心人提交了酷我的修复代码，现在正在审核中。
