### ISSUE TITLE
chrome安装后无法使用 显示已被下架 Edge也是

### ISSUE THREAD

**Issue by Charry123453** [listen1/listen1_chrome_extension#1058]
前两天浏览器文件夹被误删了 插件显示已损坏 无法恢复 就尝试去扩展商店里找 找不到 又跑到GitHub来下 发现只有源码 就回去打包安装 安装后显示又打不开 于是只能去某下载站下了个旧版本用 我想知道这是什么情况 后续还会继续开放使用吗 还是说因为法律纠纷被永久下架了？

**Comment by listen1** [comment]
https://github.com/listen1/listen1_chrome_extension/issues/1026
