### ISSUE TITLE
各大平台的VIP才能听的音乐都不能听了

### ISSUE THREAD

**Issue by bubuda** [listen1/listen1_chrome_extension#1059]
之前，各大平台的VIP都是能听的，比如：周杰伦的，咪咕是可以听的；现在都听不了；5555555

**Comment by bubuda** [comment]
看来是听不了咯！！！

**Comment by listen1** [comment]
感谢反馈，在v2.28.0中修复了该问题，详情请见 https://github.com/listen1/listen1_chrome_extension/pull/1068
