### ISSUE TITLE
部分 API 失效

### ISSUE THREAD

**Issue by scientificworld** [listen1/listen1_chrome_extension#1116]
目前已经观察到的：
- [ ] QQ 部分音乐无法播放（挺玄学，没找到规律）
- [ ] 酷狗 ~~部分音乐只能播放很短的试听部分（猜测是限制只能客户端播放了）~~ 现在全都没法放了
- [ ] 酷狗 无法查看部分歌手信息（这个应该是搜索的 API 里面缺数据，歌手信息 API 本身好像没什么问题）
- [ ] Bilibili 无法查看歌手信息（疑似用户 API 升级）#1131

**Comment by Plovor** [comment]
同，QQ音乐的都听不了了
