### ISSUE TITLE
这个软件的原理是什么?

### ISSUE THREAD

**Issue by cuixiping** [listen1/listen1_chrome_extension#1128]
没有会员权限时,  不是无法获得完整歌曲的吗? 还是说这些音乐平台的接口并没有鉴权, 只是在app界面上做了些限制?
音乐平台官方app里是无法播放或最多只能前多少秒

**Comment by mybna134** [comment]
你抓一下包就知道了，如果是vip音乐它会自动从其他音乐平台搜索相同音乐拿来播放
