### ISSUE TITLE
Firefox:      can’t be installed

### ISSUE THREAD

**Issue by bupt2017** [listen1/listen1_chrome_extension#114]
This add-on could not be installed because it appears to be corrupt

**Comment by vxxholic** [comment]
1. 将根目录下manifest_firefox.json替换为manifest.json
2. 在火狐中打开about:debugging#addons
3. 启用附加组件调试
4. 临时载入附加组件
5. 打开manifest.json

虽然重启浏览器后就要重新加载，不过至少凑合能用（火狐版本号57.0.3 )

我尝试过用web-ext打包以后签名，结果报了6个错误

>1. "/background/presistent" is not a valid key or has invalid extra properties
> 
> 错误: Your JSON file could not be parsed.
>2. "/background/scripts" is not a valid key or has invalid extra properties
> 
> 错误: Your JSON file could not be parsed.
>3. "/background/page" is a required property
> 
> 错误: See https://mzl.la/1ZOhoEN (MDN Docs) for more information.
> manifest.json
> 4."/background" should match some schema in anyOf
> 
> 错误: Your JSON file could not be parsed.
> 5.Banned 3rd-party JS library
> 
> 错误: Your add-on uses a JavaScript library we consider unsafe. Read more: https://bit.ly/1TRIyZY
> js/vendor/angular.min.js
> 6.Banned 3rd-party JS library
> 
> 错误: Your add-on uses a JavaScript library we consider unsafe. Read more: https://bit.ly/1TRIyZY
> js/vendor/jquery-1.12.2.js

**Comment by yfdyh000** [comment]
https://github.com/yfdyh000/listen1_extension
