### ISSUE TITLE
现在只有一半平台可以听了

### ISSUE THREAD

**Issue by cjcchester** [listen1/listen1_chrome_extension#1159]
![image](https://github.com/listen1/listen1_chrome_extension/assets/87079803/2bc70df3-aabe-4657-bb6d-9bb4960fc906)
![image](https://github.com/listen1/listen1_chrome_extension/assets/87079803/9e4c96ed-1d93-479c-acae-828349ac8756)
![image](https://github.com/listen1/listen1_chrome_extension/assets/87079803/bae500a6-fa04-4d93-bef3-c9e0b2becc52)
如图，qq、酷我、咪咕都不能听了，现在还能听的是网易云、b站、千千。
作者还有维护的精力吗？如果没有也麻烦说一下，谢谢

**Comment by zhiquanchi** [comment]
有的平台修改了接口，就不允许播放了。作者可能没有那么多的时间来维护，建议直接用bilibili的那个听歌，目前还没有限制。

**Comment by cjcchester** [comment]
> 有的平台修改了接口，就不允许播放了。作者可能没有那么多的时间来维护，建议直接用bilibili的那个听歌，目前还没有限制。

没事，已经跑路了，换到另一个了。

**Comment by zhiquanchi** [comment]
> > 有的平台修改了接口，就不允许播放了。作者可能没有那么多的时间来维护，建议直接用bilibili的那个听歌，目前还没有限制。
> 
> 没事，已经跑路了，换到另一个了。

换到哪个上面了，也带我一个

**Comment by cjcchester** [comment]
> > > 有的平台修改了接口，就不允许播放了。作者可能没有那么多的时间来维护，建议直接用bilibili的那个听歌，目前还没有限制。
> > 
> > 
> > 没事，已经跑路了，换到另一个了。
> 
> 换到哪个上面了，也带我一个

落雪，lx-music，但是也被制裁了，要换成六音音源。歌单迁移也很麻烦，和listen 1的不一样。讲道理也不知道能活多久，如果有条件，也可以搞自己的云音乐。

**Comment by zhiquanchi** [comment]
> > > > 有的平台修改了接口，就不允许播放了。作者可能没有那么多的时间来维护，建议直接用bilibili的那个听歌，目前还没有限制。
> > > 
> > > 
> > > 没事，已经跑路了，换到另一个了。
> > 
> > 
> > 换到哪个上面了，也带我一个
> 
> 落雪，lx-music，但是也被制裁了，要换成六音音源。歌单迁移也很麻烦，和listen 1的不一样。讲道理也不知道能活多久，如果有条件，也可以搞自己的云音乐。

看来还是要返璞归真，回到下载音乐到本地，然后在播放的方式上去。
