### ISSUE TITLE
展示一下我稍微改造的新设计

### ISSUE THREAD

**Issue by simline** [listen1/listen1_chrome_extension#1169]
![listen 1](https://github.com/listen1/listen1_chrome_extension/assets/14953917/b7e60e2c-a3f1-4dbd-8404-b686f91f992c)

**Comment by vvlol** [comment]
挺好看哦

**Comment by smsice** [comment]
可惜软件不更新了

**Comment by simline** [comment]
版权的时代，唉

在 2024-02-20 07:57:39，smsice ***@***.***> 写道：


可惜软件不更新了

**Comment by qqJoker** [comment]
求设计图，正好我想自己写一个播放器

**Comment by simline** [comment]
这不是设计图，是修改代码之后的效果



在 2024-04-19 17:20:14，"qqJoker" ***@***.***> 写道：

求设计图，正好我想自己写一个播放器

**Comment by TimemachineT** [comment]
项目是开源的,可以提交代码试试

**Comment by jdAction** [comment]
> 这不是设计图，是修改代码之后的效果 在 2024-04-19 17:20:14，"qqJoker" ***@***.***> 写道： 求设计图，正好我想自己写一个播放器 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

老哥重新发布下新的代码库，插件我看看怎么打包，顺手加个倍速功能。tnnd只能靠自己动手丰衣足食

**Comment by jdAction** [comment]
> ![listen 1](https://private-user-images.githubusercontent.com/14953917/305126538-b7e60e2c-a3f1-4dbd-8404-b686f91f992c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNDI5NDgsIm5iZiI6MTcyMDE0MjY0OCwicGF0aCI6Ii8xNDk1MzkxNy8zMDUxMjY1MzgtYjdlNjBlMmMtYTNmMS00ZGJkLTg0MDQtYjY4NmY5MWY5OTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDAxMjQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MTBmMGVlOGY5M2YxOTM1NzRmMzNlYTcxNmNjZTRkOTViNWFiYTdhNjY5NGY5MTBmOTUxMWFkMjI2ZGMzMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gDXr81Me5Ti6Jp1hharfCXbIHdnelGe7_kFBk3zHN_E)

有空的话回我消息,你的ui挺好看的,我这边把倍速功能搓出来了,看看你的代码能否分享出来?不行就整个新分支把

**Comment by simline** [comment]
@jdAction [done](https://github.com/simline/listen1_chrome_extension)
