### ISSUE TITLE
打包成crx后添加扩展，提示“此扩展程序可能已损坏。”

### ISSUE THREAD

**Issue by Leoongithub** [listen1/listen1_chrome_extension#117]
已用组策略添加白名单但无效。以目录的形式加载插件可以正常使用，但是每次启动chrome会有提示。
可能跟chrome版本有关，这个问题在升级到chrome63之后才出现。
Listen 1版本：1.2.2、1.2.4
Chrome版本：63.0.3239.108

**Comment by listen1** [comment]
请使用开发者模式加载，可以参考https://zhuanlan.zhihu.com/p/30168722
