### ISSUE TITLE
edge的两个扩展到底哪个李逵李鬼？

### ISSUE THREAD

**Issue by MC-dusk** [listen1/listen1_chrome_extension#1179]
前情提要：
#580 #767 #938 

edge扩展商店有两个扩展：

1. https://microsoftedge.microsoft.com/addons/detail/listen-1/bcneiehcbgahghfmgigmblcgkhihehad
2. https://microsoftedge.microsoft.com/addons/detail/%E5%9C%A8%E7%BA%BF%E9%9F%B3%E4%B9%90%E7%9B%92/olaohimdpfifjlhlinbpcomealcebinf

按照之前的讨论结果，第一个是官方维护的，曾经DMCA下架，后又恢复。

仓库的readme给的是第一个链接，但是如果直接在扩展商店搜索listen1，是搜不到这个的，只能搜到第二个；第二个的下载使用量和评分人数也更高。

前者版本更新到2023年8月3日，后者停留在2022年12月19日。

如果说前者是所谓的“官方正品”，为什么前者简介又强调“扩展非上传者制作，上传者仅将其打包并作出细节修改，版权归原作者所有”？

**Comment by dhxh** [comment]
1、edge发布渠道是我在维护。最开始的时候edge商店是没有listen1，我发邮件征求了作者，获得作者授权搬运到edge商店。
2、listen1之前收到网易云dmca，导致下架一段时间，我屏蔽了网易云，重新上传商店，评分人数和下载量重新开始计算。

**Comment by mikelxk** [comment]
官方没有维护edge扩展，第一个是 @dhxh 维护的，然后第二个是李鬼, 改了扩展的权限和添加了些加密过的代码
