### ISSUE TITLE
播放版权音乐时，会循环弹出提示

### ISSUE THREAD

**Issue by terencehyz** [listen1/listen1_chrome_extension#124]
![](https://ws1.sinaimg.cn/large/77ce63b1ly1fnpi0pf92sj211q0mkq5f.jpg)

https://ws1.sinaimg.cn/large/77ce63b1ly1fnpi0pf92sj211q0mkq5f.jpg

**Comment by listen1** [comment]
https://github.com/listen1/listen1_chrome_extension/pull/393
此次更新修复了循环弹出提示的问题
