### ISSUE TITLE
火狐浏览器安装失败?

### ISSUE THREAD

**Issue by hejingsong** [listen1/listen1_chrome_extension#127]
Firefox Quantum V58.0.1 64bit
windows7 sp1 64bit
安装时出现
该附加组件无法安装，因为它似乎已损坏。

**Comment by listen1** [comment]
直接打包xpi方式可能无法安装，请尝试在附加组件中允许`启用附加组件调试`, 点击`临时载入附加组件`后载入xpi方式使用。
若在右上方看不到Listen1的图标，请在`定制`中拖动Listen1图标到右上角

**Comment by listen1** [comment]
另外，在打包前需要把 
`    "background": {
        "presistent": true,
        "scripts": ["js/background.js" ]
    },`
修改为
`
    "background": {
        "scripts": ["js/background.js" ]
    },
`
否则会报错

**Comment by listen1** [comment]
firefox 插件下载地址：https://addons.mozilla.org/zh-CN/firefox/addon/listen-1/

**Comment by hejingsong** [comment]
OK。已解决。新年快乐。
