### ISSUE TITLE
 Firefox 版插件无法正常使用

### ISSUE THREAD

**Issue by vxxholic** [listen1/listen1_chrome_extension#130]
播放任意一首歌曲提示“版权原因无法播放，请搜索其他平台”

插件版本1.5.1
Firefox 57.0.4 (64 位)

**Comment by listen1** [comment]
请检查vpn设置或网络设置，如还有疑问，能否提供开发者工具console报错的截图，谢谢！

**Comment by vxxholic** [comment]
抱歉，为了调试另一个bug打开了vpn，忘记关了…………【然而并没有再次触发那个bug
