### ISSUE TITLE
强烈建议能显示歌单的地址

### ISSUE THREAD

**Issue by heartacker** [listen1/listen1_chrome_extension#14]
比如网易云音乐。我觉得这个歌单不错。但是我该怎么点击这个歌单然后收藏呢？只能给出了单个歌曲的链接，能不能给我歌单的链接，谢谢
![qq 20160506101952](https://cloud.githubusercontent.com/assets/1876302/15062597/1a944254-1374-11e6-9212-e696036e45ad.png)

**Comment by listen1** [comment]
已经在最新版中加入，enjoy
