### ISSUE TITLE
为什么新版显示不了歌词了

### ISSUE THREAD

**Issue by atest1** [listen1/listen1_chrome_extension#141]
之前的1.2.1用着挺正常的。春节试了一下新版就发现歌词显示不了，今天试了下1.6.0这个问题依然存在，难道是我环境的问题？才刚重装了系统啊。Win10 1703
不论是Windows 64位桌面版还是Chrome插件版都是一样的结果，播放列表正常显示，但是位置右移到右边界了。
![image](https://user-images.githubusercontent.com/6992572/39436924-f766cf10-4cd1-11e8-8a2b-542889fadeb0.png)

1.2.1桌面版的界面是这样的：
![image](https://user-images.githubusercontent.com/6992572/39437046-4df2ddec-4cd2-11e8-863e-a28bd52d7a21.png)

**Comment by listen1** [comment]
你好，改版后歌词显示的地方变了。点击歌曲的封面图片就能显示了。

**Comment by atest1** [comment]
哎呀，怎么改了这样的方式，看起来界面缺了一截，挺难看的

**Comment by amplersir** [comment]
下载好，还显示歌词 ，现在也不显示了 也不知道在哪里调
