### ISSUE TITLE
QQ音乐播放不了

### ISSUE THREAD

**Issue by jiangqc5656** [listen1/listen1_chrome_extension#147]
不知道是不是我网络的原因 还是QQ又更换地址了？
所有的QQ音乐都播放不了

**Comment by wen4034** [comment]
没用

**Comment by noschoollee** [comment]
我fork了一份，并修改了qq音乐api，目前可以正常播放了，请试试

**Comment by lenghonglin** [comment]
测试了一下，的却是qq音乐不能播放

**Comment by noschoollee** [comment]
var qq_bootstrap_track = function(sound, track, success, failure, hm, se) {
        var target_url ='https://c.y.qq.com/base/fcgi-bin/fcg_music_express_mobile3.fcg?g_tk=195219765&jsonpCallback=MusicJsonCallback004680169373158849&loginUin=1297716249&hostUin=0&format=json&inCharset=utf8&outCharset=utf-8&notice=0&platform=yqq&needNewCode=0&cid=205361747&callback=MusicJsonCallback004680169373158849&uin=1297716249&songmid='+ track.id.slice('qqtrack_'.length) +'&filename=C400'+ track.id.slice('qqtrack_'.length) + '.m4a&guid=7332953645';

        hm({
            url:target_url,
            method: 'GET',
            transformResponse: undefined
        })
        .then(function(response) {
            var data = response.data;
            data = data.slice(data.indexOf('(')+1,data.length-1);
            data = JSON.parse(data);
            var token = data.data.items[0].vkey;
            var url = 'http://dl.stream.qqmusic.qq.com/C400' +  track.id.slice('qqtrack_'.length)  + '.m4a?vkey='+ token + '&uin=1297716249&fromtag=0&guid=7332953645';
            sound.url = url;
            success();
        });
    }

**Comment by noschoollee** [comment]
[qq.txt](https://github.com/listen1/listen1_chrome_extension/files/2053176/qq.txt)
重命名成qq.js，替换\js\provider\里的就行

**Comment by listen1** [comment]
已经用@noschoollee的方案修复了qq音乐的播放，最新版本1.6.1，感谢！

**Comment by noschoollee** [comment]
@listen1 https://blog.csdn.net/dwf_h/article/details/79990470 这是api来源，我只是做了处理，我很喜欢您的项目，也感谢您

**Comment by WindHunting** [comment]
您好，我非常喜欢您的项目。目前1.6.1这里qq依然无法播放。

**Comment by WindHunting** [comment]
你好，是1.6.1里的js不对。实际上按2楼的api是可以用的。已修复。

**Comment by noschoollee** [comment]
@WindHunting，2楼的api音质比较差，是c100，1.6.1里用的是c400最高音质，我目前用下来没有什么问题，你可以是一下把c400这部分换成c200试试，因为作者之前用的一直是c200

**Comment by WindHunting** [comment]
@noschoollee  谢谢。 但是我测试了1.6.1是不能用的，这里是海外。那个api似乎c200也不行。另外我留意到sonimei是m800，谁对他们那个接口有头绪么？ 我这里就是只有2楼的才能用。

**Comment by noschoollee** [comment]
@WindHunting，那就是版权问题了

**Comment by WindHunting** [comment]
@noschoollee 我正在测试，我觉得是分接口的。 首先前几天1.6.0是可以用的！ 其次比如sonimei的那个接口也是可以用的！

**Comment by noschoollee** [comment]
@WindHunting， 我看了一下，他们获取vkey是从他们的服务器，并不是从你本地直接获取，我觉得应该就是版权问题

**Comment by noschoollee** [comment]
@WindHunting，我试了试m800也是可以的，获取vkey的方式一样

**Comment by noschoollee** [comment]
@WindHunting，我挂了翻墙，确实无法获取了

**Comment by WindHunting** [comment]
@noschoollee 很感谢，确实是这个原因，我测试了各种参数，2楼的可以用。 这样要么1.用2楼的低音质参数 2. 试着调用另外的接口

**Comment by noschoollee** [comment]
@WindHunting，一个不幸的消息，sonimei做了防跨域

**Comment by WindHunting** [comment]
@noschoollee   我经过非常详细的测试。 发现： 首先问题确实就是海外墙。
解决方法：1. 套用2楼低音质接口，目前没有被墙
2. 套用别的接口
* 首先我详细测试，发现无论是这里1.6.1的vkey获取还是sonimei(实际上和2333一样的接口)的vkey全部是有效的。海外无法使用的原因是连y.qq被拦，我测试是vkey返回空值，直接用的话由于unblock youku就可以使用。

所以我有个疑问是**能否让unblock youku在这个插件里也同时生效？**
目前我的临时解决方案是在1. 加上 url获取后替换到正常别的方法抓的url.

**Comment by noschoollee** [comment]
@WindHunting，用unblockyouku的dns或者pac

**Comment by WindHunting** [comment]
@noschoollee 是的，我自己那个方案放高音质也挺好的。
pac什么的一定程度上可以，不过这都是外部方案呀，如果能在内部解决就好了。

**Comment by twentyoneisawesome** [comment]
請問海外 使用 http://ws.stream.qqmusic.qq.com/C100 
還可以播放嗎？
