### ISSUE TITLE
[feature request]希望增加在当前激活的tab页显示歌词的功能

### ISSUE THREAD

**Issue by mu-yu** [listen1/listen1_chrome_extension#148]
就像这样：

![image](https://user-images.githubusercontent.com/3822774/40959951-d3645a5e-68d0-11e8-9425-4e93dbed1ca5.png)

**Comment by WindHunting** [comment]
@mu-yu  其实有歌词的，在播放器的歌名页面。 这其实是个ui问题， 调整后问题都不大。

**Comment by dingdingrao** [comment]
这个功能加在桌面版还不错，要是加在浏览器的每个窗空中，不是很有必要的感觉，得不偿失啊~
