### ISSUE TITLE
希望增加在“我的歌单”里搜索歌曲的功能

### ISSUE THREAD

**Issue by atest1** [listen1/listen1_chrome_extension#150]
有时候不确定一首歌是否已添加到自己的歌单里，如果能增加一个搜索“我的歌单”的功能就好了。

另外现在播放列表既然左边缺了一块，能否增加一列专辑名呢，就好象歌单里那样。这样就可以直接点击一下打开专辑列表了（以前是点击图片进入的，现在点击图片进入歌词，要进入专辑的话需要从歌词界面再点击专辑名字）

**Comment by listen1** [comment]
https://github.com/listen1/listen1_chrome_extension/commit/decaccf1c921061b4efd89693befae9a0f005f7c 加入了歌单内搜索功能

点击播放栏的专辑名可以打开专辑
