### ISSUE TITLE
可能海外导致，酷狗的歌单和搜索均为空。

### ISSUE THREAD

**Issue by WindHunting** [listen1/listen1_chrome_extension#152]
qq的js我自己改了可用。 酷狗还没深入看，怀疑是海外的原因。

另外建议修改主界面歌曲显示，例如有些歌显示是灰色，但是添加到播放列表后，在播放列表内可以播放。有空可以修复一下这个，或者我有空也会调一下 :)

**Comment by WinterXMQ** [comment]
是海外ip导致的

**Comment by WindHunting** [comment]
@WinterXMQ  是的，qq我改通了，酷狗我弄了半天有点难，接口不通，可能比较实际的方法是服务器或者vpn，pac搞不定。

**Comment by WinterXMQ** [comment]
大多数的api是在网上找的，不是自己抓包的，你这个问题的话，估计得重新选择api了
我抽空重新试试

**Comment by WinterXMQ** [comment]
我新加了酷我的支持，但是现在在建立pr的时候，发现这个pr是针对第一次fork的时候的，我都不知道怎么提交了
![20180613224643](https://user-images.githubusercontent.com/3694982/41358885-e2c4efe0-6f5b-11e8-81a8-5b32934f82c3.png)

**Comment by WindHunting** [comment]
@WinterXMQ  kugou估计难，我试了，搜都不给的，常规unblock方法也不好使。我想的是能不能通过比如第三方2333抓到结果，然后直接读它的地址。读到的最终地址是可以放的。

**Comment by WindHunting** [comment]
@WinterXMQ 这个你改一下，把base做成自己，head做成listen1, 然后Merge.

**Comment by WinterXMQ** [comment]
能力有限，git只会最简单的，没搞明白怎么回事

**Comment by WindHunting** [comment]
@WinterXMQ  哈哈，很好了，自发性学习比被动式强。

**Comment by WinterXMQ** [comment]
![qq 20180614084757](https://user-images.githubusercontent.com/3694982/41385697-d7fc5112-6faf-11e8-9105-a599fe8c2b49.jpg)
话说这个是怎么实现的，我做了merge，与作者的分支点是好几天前的

**Comment by WindHunting** [comment]
@WinterXMQ  你用PR把listen1反向merge到自己的。

**Comment by WindHunting** [comment]
@WinterXMQ 厉害了，我试了feature的api，确实可以。稍微看了下，那个接口确实说得通。 @listen1 建议update WinterXMQ feature上的kugou

**Comment by WinterXMQ** [comment]
这个接口用的是网页端的，目前存在的问题就是有些歌不允许网页播放（能够获取到地址，但就是不能播放），还有就是你说海外访问的速度比较慢

**Comment by Xiaotouming** [comment]
所以现在这么问题还没解决么，酷狗酷我海外ip无结果

**Comment by listen1** [comment]
应该是海外IP限制导致的，后续可能通过添加代理设置的方式解决此问题。
