### ISSUE TITLE
歌单的无版权歌曲

### ISSUE THREAD

**Issue by kamijiang** [listen1/listen1_chrome_extension#154]
歌单中如果存在平台无版权歌曲时播放到该歌曲会卡住不动，而不是跳过，就好像卡主一样

**Comment by WinterXMQ** [comment]
提供歌曲所属的乐库和歌曲编号（或者其他具体的信息，方便确定无版权的歌曲）

**Comment by listen1** [comment]
https://github.com/listen1/listen1_chrome_extension/pull/393
此次更新解决了部分播放卡住的问题
