### ISSUE TITLE
可否增加歌单搜索功能

### ISSUE THREAD

**Issue by dajjdeshuo** [listen1/listen1_chrome_extension#158]
listen1目前曲库源已经比较完善，搜歌功能也很强大。但是可否考虑增加歌单搜索功能，因为首页推荐的歌单不一定符合口味，目前对于喜欢的歌单，只能一个个歌曲搜索后添加到自己的歌单，或者在歌单列表中肉眼搜索后加入播放列表。

**Comment by Dumeng** [comment]
可以在对应提供网站搜索到歌单，将地址复制下来，在“我的歌单”Tab右边通过“打开歌单”导入

**Comment by listen1** [comment]
已经在v2.17.0版本中初步提供了歌单搜索功能（支持网易云），感谢你的反馈
