### ISSUE TITLE
虾米的接口变了？浏览器插件里所有与虾米有关的功能都用不了了

### ISSUE THREAD

**Issue by vxxholic** [listen1/listen1_chrome_extension#164]
Firefox和Chrome都是这样

**Comment by listen1** [comment]
初步研究，虾米接口加入了反爬虫，反盗链的一些机制：
1. 访问 www.xiami.com 的请求，user-agent字段必须和referer一致。user-agent为pc，refer为m.xiami.com时将被拒绝。（此处修改refer值就能解决）
2. 访问 api.xiami.com 的请求，首次请求将需要滑动滑块验证，一些情况下会要求登录后访问。（此问题还在研究解决方案）

**Comment by vxxholic** [comment]
Windows 10（1803）上的Firefox 61.0.2 (64 位)无法使用此插件，提示“此附加组件不适用您的平台。”

**Comment by hanzichi** [comment]
虾米还是不行吧？快速搜索那边直接挂了.. @listen1

**Comment by Stuip** [comment]
虾米音乐快速搜索那边一直处于加载状态 @listen1
