### ISSUE TITLE
网易云的音乐听不了？

### ISSUE THREAD

**Issue by lychangyong** [listen1/listen1_chrome_extension#17]
虾米和QQ音乐的音乐能正常听。可是网易云的音乐总是停在 0：00/0：00，不过在列表页面还能加载歌词？

**Comment by listen1** [comment]
可以检查一下vpn设置，刷新页面。如果还是不行，麻烦看一下开发者选项中console的报错输出，能复制给我看一下吗?谢谢

**Comment by listen1** [comment]
#6 possible duplicated

**Comment by lychangyong** [comment]
重启了一下浏览器，再试了一下发现就可以听了。
