### ISSUE TITLE
感谢dalao，请问可否增加歌词翻译功能？

### ISSUE THREAD

**Issue by kroggan** [listen1/listen1_chrome_extension#172]
RT。。。网易云上会直接提供歌词原文及中文翻译，请问能不能增加这一功能。。。   再次感谢开发者dalao们。。。

**Comment by listen1** [comment]
你好，已经在v2.17.0中加入了歌词翻译功能，感谢你的建议

**Comment by kroggan** [comment]
感谢回复，祝你身体健康，生活愉快！
