### ISSUE TITLE
方便是好，尊重版权。

### ISSUE THREAD

**Issue by duccck** [listen1/listen1_chrome_extension#18]
listen1可以免费收听付费歌曲，还请速速改正这个bug。

**Comment by listen1** [comment]
请说一下平台名称和歌曲名称，谢谢

**Comment by Tacalb9507** [comment]
QQ音乐平台 霉霉的收费专辑1989就可以在listen1直接收听 刚发现的

**Comment by listen1** [comment]
好的，找到原因了，是网站API中遗留的试听地址，正在修复这个bug。

**Comment by mu228** [comment]
请问可否做成网页版的?移动设备也可以听歌.本地加载不安逸

**Comment by jiangbeth** [comment]
疯了吗？？？？？？为什么取消？？？

**Comment by listen1** [comment]
在1.1版本中修复了相关问题。
