### ISSUE TITLE
火狐官方扩展页吞了

### ISSUE THREAD

**Issue by mraandtux** [listen1/listen1_chrome_extension#181]
[火狐官方扩展页吞了](https://addons.mozilla.org/firefox/addon/listen-1/)，是否考虑把已打包的xpi文件上传到releases？我照了 readme.md 的做法都显示“扩展已损坏”的提示，只能通过调试页临时加载。

**Comment by listen1** [comment]
感谢反馈。火狐官方插件因为如下原因将listen 1插件下架了：
1) JQuery 2.* is no longer accepted. Please use JQuery 3.*
We accept JQuery/JQuery-UI libraries downloaded from 'ajax.googleapis.com', 'jquery.com' or  'jqueryui.com'; and used without any modification (downloaded and not copy pasted). Minified versions are better. (file-name change does not matter)
We do not accept modified, re-configured or customized libraries.
Please use non-custom versions of jquery-ui, as well as the stock version of jquery and others, that match the original checksums on the maintainer's website.
Eg:
js/vendor/jquery-2.2.3.min.js

2) We do not accept Angular 1.* any more, please upgrade Angular or use any other frame work.
Eg. js/vendor/angular.min.js 

需要重新上架可能需要一定时间，主要是angular 1.x的迁移。不知道有没有什么好的建议

**Comment by yfdyh000** [comment]
@listen1 [下载最新版](https://angularjs.org/)就可以，https://github.com/mozilla/addons-linter/blob/master/docs/third-party-libraries.md 为`We allow the latest 1.x version at submission time`，经测1.7.5可行。
升jquery 3只有小bug，#95。

顺便，对 #94 有何看法。

**Comment by listen1** [comment]
感谢反馈，在1.9.1版本中修复了该问题, 火狐插件已经重新上架

**Comment by listen1** [comment]
火狐再次下架

Details:
This add-on didn&#39;t pass review because of the following problems:

1) We do not accept Angular 1.* any more, please upgrade Angular or use any other frame work.
Eg. js/vendor/angular.min.js 

Please fix them and submit again. Thank you.

**Comment by yfdyh000** [comment]
@listen1 是审核员驳回了吗，向他问一问`We do not accept Angular 1.* any more`的来源，将 https://github.com/mozilla/addons-linter/blob/master/docs/third-party-libraries.md#angularjs-1x 给他看一下。或者考虑签名后自行分发，目前仍能通过。

**Comment by linsui** [comment]
请问有什么进展吗？

**Comment by caliban511** [comment]
求火狐扩展版。

**Comment by listen1** [comment]
火狐插件地址 https://addons.mozilla.org/zh-CN/firefox/addon/listen1/
