### ISSUE TITLE
1.9.0的网易云的歌单只能显示第一首歌

### ISSUE THREAD

**Issue by wuchangmin** [listen1/listen1_chrome_extension#182]
自从1.8.0升到1.9.0发现网易云的歌单显示不完整
![image](https://user-images.githubusercontent.com/10378179/49709209-388a7400-fc6e-11e8-8558-a09c681689aa.png)

**Comment by listen1** [comment]
初步判断是网易云限制了API的使用规则，需要Cookie才能看到完整内容。如果遇到此问题，可以访问网易云的网页端访问一次就能恢复了。
后续将在listen1中解决此问题。感谢反馈。

**Comment by wuchangmin** [comment]
非常感谢！！！
