### ISSUE TITLE
Listen V2.0 将在2018年底发布

### ISSUE THREAD

**Issue by listen1** [listen1/listen1_chrome_extension#185]
![preview](https://user-images.githubusercontent.com/18599108/50205011-c28ab900-03a1-11e9-8cba-1e99653840b3.png)

Listen1新版本2.0正在紧张测试中，预计在2018年年底发布。

新版本预计上线的功能：
- 新版UI，更加友好，流畅的体验, designed by iparanoid
- 修复虾米音乐歌单API的bug
- 修复酷狗音乐部分歌单的歌曲无法播放的bug
- 修复github无法导入歌单的bug
- 修复一些平台的歌单无法打开的bug
- 增加bilibili曲库
- 客户端版本支持全局快捷键
- 升级部分依赖代码库

**Comment by Dumeng** [comment]
能否提升为TypeScript？可维护性更好

**Comment by bingoy2k** [comment]
大佬能否有个MAC下详细一点的编译教程？

**Comment by listen1** [comment]
1. 歌词功能点击专辑头像就能看到，可能没有足够的提示。桌面歌词的功能暂时还未提供。
2. 日推是每日推荐吗？

**Comment by listen1** [comment]
@bingoy2k mac编译请访问桌面版网站：https://github.com/listen1/listen1_desktop

**Comment by huangzi959** [comment]
今天用上新版了,很喜欢,感谢大佬的付出

**Comment by ithg** [comment]
> 1. 歌词功能点击专辑头像就能看到，可能没有足够的提示。桌面歌词的功能暂时还未提供。
> 2. 日推是每日推荐吗？

日推是每日推荐 感觉蛮需要的 要不然就得先打开网易云听一遍日推，然后把喜欢的再转到listen1上 有点麻烦，导致在listen1上是一直听听过的歌😂
