### ISSUE TITLE
“版权原因无法播放 请搜索其他平台”

### ISSUE THREAD

**Issue by wxy4th** [listen1/listen1_chrome_extension#195]
我搜“打上花火” 灰色的歌名无法直接播放 会提示版权原因 但是点链接进去是可以播放的 不存在付费或者会员之类的问题 这应该是个错误吧

**Comment by listen1** [comment]
确认为bug，将尽快修复，感谢反馈

**Comment by LostZX** [comment]
是不是存在会员歌曲无法播放呀。。。桌面版的

**Comment by bofeiw** [comment]
“版权原因无法播放 请搜索其他平台” 这句话会无限循环提示

**Comment by laike9m** [comment]
Same here.

**Comment by listen1** [comment]
https://github.com/listen1/listen1_chrome_extension/pull/393
此次更新修复了循环提示的问题
