### ISSUE TITLE
回车搜索功能

### ISSUE THREAD

**Issue by sunshine940326** [listen1/listen1_chrome_extension#203]
![image](https://user-images.githubusercontent.com/20368358/51456541-01d56c80-1d89-11e9-9940-b24d3dab9dde.png)

这里，希望可以增加回车搜索功能

**Comment by listen1** [comment]
你的意思是按下回车时立刻搜索而不需要等待一个小的延时？

**Comment by listen1** [comment]
已经在最新版本中支持，谢谢反馈
