### ISSUE TITLE
虾米音乐无法搜索

### ISSUE THREAD

**Issue by snowWave1995** [listen1/listen1_chrome_extension#204]
虾米音乐无法搜索歌曲

**Comment by Dumeng** [comment]
前往虾米网页版进行一次搜索，完成滑块验证后可以返回Listen1重试

**Comment by listen1** [comment]
请升级到新的版本，应该解决了之前虾米的问题。

**Comment by listen1** [comment]
虾米针对api会进行验证，可能需要拖动框完成验证后才能使用api

**Comment by listen1** [comment]
现在的解决方案是访问返回json中带的地址，完成滑块验证，后续可能通过内嵌验证模块或更换搜索接口的方式解决此问题
