### ISSUE TITLE
“版权原因无法播放 请搜索其他平台” 

### ISSUE THREAD

**Issue by 326068345** [listen1/listen1_chrome_extension#206]
下载的listen版本2.1.2,不管是插件还是安装版本，所有歌曲都提示这个“版权原因无法播放 请搜索其他平台” .
macOS Mojave版本10.14.2
chrome版本 71.0.3578.98（正式版本） （64 位
错误信息：
错误信息1
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem: chrome-extension-resource:". Either the 'unsafe-inline' keyword, a hash ('sha256-4i/UgFRq5GV5/zCG+l3zFewouX2lYeboafDGhFLhxvs='), or a nonce ('nonce-...') is required to enable inline execution.
上下文listen1.html堆叠追踪
		listen1.html:17 (匿名函数)
17 是以下内容：
<script>if (typeof module === 'object') {window.module = module; module = undefined;}</script>

错误2
错误信息和上面相同，下是不同之处
上下文listen1.html堆叠追踪
		listen1.html:44 (匿名函数)
44 是以下内容
   <script>if (window.module) module = window.module;</script>

错误3
pascalprecht.translate.$translateSanitization: No sanitization strategy has been configured. This can have serious security implications. See http://angular-translate.github.io/docs/#/guide/19_security for details.

上下文listen1.html堆叠追踪
		js/vendor/angular.min.js:127 (匿名函数)
		js/vendor/angular-translate.min.js:6 (sanitize)
		js/vendor/angular-translate.min.js:6 (t.interpolate)
		js/vendor/angular-translate.min.js:6 (d)
		js/vendor/angular-translate.min.js:6 (j.instant)
		js/app.js:130 (Object.keys.forEach)
		js/app.js:129 ($http.get.then)
		js/vendor/angular.min.js:140 (匿名函数)
		js/vendor/angular.min.js:151 ($digest)
		js/vendor/angular.min.js:155 ($apply)
		js/vendor/angular.min.js:106 (k)
		js/vendor/angular.min.js:111 (w)
		js/vendor/angular.min.js:112 (E.onload)

请问这个问题要怎么处理

**Comment by niudiewei** [comment]
感觉这个走到头了

**Comment by 326068345** [comment]
> 感觉这个走到头了

哎，多好用的插件啊

**Comment by Dumeng** [comment]
以上报错是由于CSP设置引起，报错部分用于桌面版打包，不影响插件版本。

大量出现“版权原因无法播放 请搜索其他平台”可能是海外IP受限，请前往对应平台网页版尝试是否能够播放。

**Comment by bwxz** [comment]
> > 感觉这个走到头了
> 
> 哎，多好用的插件啊

哎，都怪发展太快了，用户估计好多了，被tx发现了，然后呜呜呜了~~

**Comment by listen1** [comment]
请检查是否使用了VPN工具，导致访问时被认定为海外IP地址。

**Comment by 326068345** [comment]
> 请检查是否使用了VPN工具，导致访问时被认定为海外IP地址。

我是在海外，应该是ip的问题。listen1能解决这个问题吗，我这里不让拨vpn，使用http代理又直接无法访问。

**Comment by listen1** [comment]
> > 请检查是否使用了VPN工具，导致访问时被认定为海外IP地址。
> 
> 我是在海外，应该是ip的问题。listen1能解决这个问题吗，我这里不让拨vpn，使用http代理又直接无法访问。

海外暂时只能通过挂国内的vpn解决。你也可以尝试socks5代理，比如shadowsocks。

**Comment by 326068345** [comment]
好的

**Comment by yuanchuan666** [comment]
> > > 请检查是否使用了VPN工具，导致访问时被认定为海外IP地址。
> > 
> > 
> > 我是在海外，应该是ip的问题。listen1能解决这个问题吗，我这里不让拨vpn，使用http代理又直接无法访问。
> 
> 海外暂时只能通过挂国内的vpn解决。你也可以尝试socks5代理，比如shadowsocks。

为啥挂vpn就出现该问题呢

**Comment by Y-Ayame** [comment]
没救了吗？用习惯了，虽然有绿钻有黑胶。但歌都分散不全，已经不想再给各个平台充钱了
