### ISSUE TITLE
网易云音乐的歌曲都播放不了了,,,

### ISSUE THREAD

**Issue by AAAKgold** [listen1/listen1_chrome_extension#212]
网易云音乐的歌曲都播放不了了,,,

**Comment by tianyunperfect** [comment]
> 网易云音乐的歌曲都播放不了了,,,

我正在听网易云的音乐……mac客户端没有问题。

**Comment by bwxz** [comment]
> 网易云音乐的歌曲都播放不了了,,,

ver1.8.1无法播放虾米音乐；ver2.1.2无法播放QQ音乐，其他正常

**Comment by listen1** [comment]
已经修复qq音乐无法播放的问题，请升级到v2.1.3

**Comment by Vtamins** [comment]
是一个bug，我已经修复了

app.js 第716行
 $scope.showPlaylist(result.id); 修改为

$scope.showPlaylist(result.parse_url(url).id);

`
diff --git a/js/app.js b/js/app.js
index ee0fee4..84dc720 100644
--- a/js/app.js
+++ b/js/app.js
@@ -713,7 +713,7 @@ const main = () => {
         }).success((data) => {
           const { result } = data;
           if (result !== undefined) {
-            $scope.showPlaylist(result.id);
+            $scope.showPlaylist(result.parse_url(url).id);
           } else {
             Notification.info($translate.instant('_FAIL_OPEN_PLAYLIST_URL'));
           }
(END)
`
