### ISSUE TITLE
listen1可以导入本地歌曲吗

### ISSUE THREAD

**Issue by 326068345** [listen1/listen1_chrome_extension#218]
你好，我现在有一个使用场景，就是某一首歌在listen1上面所有平台的音质都不行，还有就是一首歌特定的翻唱版本或者改编版没有被平台收录。我采取的方法是到youtube找到链接，然后使用https://mp3-youtube.download/en转换为mp3并下载到本地，但是这么听起来并不方便。 所以listen1现在如何导入本地歌曲，或者在以后会支持吗。

**Comment by bwxz** [comment]
是个好想法

**Comment by listen1** [comment]
桌面版v2.17.0现在已经支持了本地音乐的导入，谢谢你的建议
