### ISSUE TITLE
连接到github失败

### ISSUE THREAD

**Issue by liuzhenyulive** [listen1/listen1_chrome_extension#221]
点击连接到Github.com并同意授权后,返回点击完成授权,可是任然没有链接上github,谢谢.

**Comment by autumnsun** [comment]
我也遇到了同样的情况，请dalao尽快修复，谢谢

**Comment by autumnsun** [comment]
我也遇到了同样的情况，请dalao尽快修复，谢谢

**Comment by listen1** [comment]
确认为bug，正在修复

**Comment by KingGeorgeWang** [comment]
给大佬补充一点点线索，这一问题在2.1.4版本也会出现，但是会有小概率连接成功（我之前大概尝试了七八次才成功。。）

**Comment by Zachary-zk** [comment]
这个BUG怎么还没有修好

**Comment by 1017098458** [comment]
连接到GitHub后，是不是可以把歌单保存到GitHub上，以后用其他电脑的时候就可以直接从GitHub上导入了？

**Comment by flyin9sky** [comment]
2.2同样遇到问题，不能同步歌单作孽啊

**Comment by listen1** [comment]
抱歉这么久修复，已经在v2.2.1中修复了此问题。感谢大家的反馈
