### ISSUE TITLE
歌手信息获取失败【网易+虾米+哔哩】

### ISSUE THREAD

**Issue by hxzqlh** [listen1/listen1_chrome_extension#223]
进入歌单后，点击中间拦的歌手链接，这几个网站的歌手信息无法获取。

![image](https://user-images.githubusercontent.com/3350776/54796727-5d8a7c00-4c8c-11e9-95e2-9b1a6af12599.png)
![image](https://user-images.githubusercontent.com/3350776/54796740-71ce7900-4c8c-11e9-98b2-abb7a7e7b762.png)
![image](https://user-images.githubusercontent.com/3350776/54796756-87dc3980-4c8c-11e9-8d7f-6ffa02470143.png)

一开始怀疑是版本原因，尝试了所有的版本发现都有这个问题。

后来分别拿插件版和桌面版的v1.8.0，对比发现桌面版的没有这个问题。

以网易为例，获取歌手信息的http请求：

插件版：
![image](https://user-images.githubusercontent.com/3350776/54798788-2ff60080-4c95-11e9-84f7-70abacccda39.png)

桌面版：
![image](https://user-images.githubusercontent.com/3350776/54798794-3f754980-4c95-11e9-815a-4b9fdc28105d.png)

应该是插件版的获取歌手信息时请求封装有问题，导致api直接返回 403 错误

**Comment by listen1** [comment]
感谢反馈，您的版本可能有点低，这些问题在新版插件中修复了。
