### ISSUE TITLE
插件版是不是被QQ限制了？

### ISSUE THREAD

**Issue by bwxz** [listen1/listen1_chrome_extension#225]
插件版是不是被QQ限制了？
QQ音乐大部分歌曲已不支持网页播放了，导致大批量的歌曲不能播放

**Comment by listen1** [comment]
感谢反馈！
QQ音乐似乎限制了非登录用户可收听歌曲的范围。
Listen1采用的均是音乐网站网页版的API，如果发现在Listen1中无法播放和收听音乐，请尝试在网页版是否有同样问题。如果网页版能听，但是Listen1内不能播放，请再提issue。

**Comment by moryxsw** [comment]
qq音乐某些歌曲要求仅限客户端播放，所以无法播放的音乐几乎都是这类歌曲
