### ISSUE TITLE
添加标签与记录

### ISSUE THREAD

**Issue by TheKiteRunning** [listen1/listen1_chrome_extension#227]
对于每一个听者，每首歌都有它特有的基因，专辑、歌单只能概括，却不能定位。不知道能否为歌曲添加一个标签维度，这样可以从另一个维度规整和定位歌曲。

另外，正如阅读，听曲也有心情也有想记录的地方，似乎所有音乐软件都不重视这一部分，不知道listen1能否作为一个音乐时光轴，记录同一首歌不同时候听到的感觉。

感谢！

**Comment by yfdyh000** [comment]
使用网易云音乐等社交化的音乐平台吧。超出该软件的范畴了。你要的应该不是个人的本地标签（tag）吧。

**Comment by TheKiteRunning** [comment]
@yfdyh000 感谢您的回复。正如读书一样，分类和记录是个人的本地行为，网易云之类的社交评论过于喧嚣。同一首歌，有作者，国家，音乐类型之类的多种维度的划分。比如我正在听的这个EF的专辑《Give Me Beauty... Or Give Me Death!》里的《Tomorrow my friend》，我希望划分为后摇和人声这几个标签。当我再想听某一个标签的时候，抽取出来就可以。

总而言之，歌单类似于categories，标签则是tags。

至于听一首歌曲时的记录，就像拿起一本书看到心动段落时的笔记。作用不必多言。

可惜豆瓣音乐与豆瓣fm脱离，不然短评本身能够起到一点作用。可惜。

只是一个想法。感谢。

**Comment by yfdyh000** [comment]
@TheKiteRunning 如果是要个人化的标签功能，那么该软件加上tags功能也未尝不可。当前的歌单功能好像与tags没太大的差别，您是否只是需要列出歌曲已被列入的歌单呢，或者歌单的隐藏/归档功能。

如果很喜欢记录随笔，推荐使用便签或知识管理类的软件，便于个人保存和修改。

**Comment by TheKiteRunning** [comment]
"列出歌曲已被列入的歌单"，这个似乎能起到标签的作用~

谢谢您
