### ISSUE TITLE
某种网络环境下，任何音乐都不能播放。而在相应的网站页面播放就没问题。

### ISSUE THREAD

**Issue by meiMingle** [listen1/listen1_chrome_extension#228]
这个问题已经困扰我很久了，希望可以得到作者帮助。如果作者有意向解决这个问题，我可以提供相应的网络环境（酸酸乳），不胜感激😁
![屏幕截图(12)](https://user-images.githubusercontent.com/39942874/56109868-ed1e0480-5f84-11e9-8763-7791d32dc6e0.png)

**Comment by liuqianghui** [comment]
这种情况应该设置chrome的流量不经过proxy，直接用国内的就好
