### ISSUE TITLE
关于项目有可能被关闭的讨论

### ISSUE THREAD

**Issue by Pekary** [listen1/listen1_chrome_extension#229]
作者3.3更新了项目可能被关闭的消息，但现在看到Issues里面主要还是在提需求，貌似对项目是否能继续下去没有太多人关心，所以开个Issue讨论一下吧。这个项目是个优秀的项目，如果有能帮得上忙的地方会出力。

**Comment by yfdyh000** [comment]
你看错了，那个通知是2017年11月底的: https://github.com/listen1/listen1_chrome_extension/commit/4c2bd7f27c31c3a8b03ccc3fb51fd7a9f7810054
首先是低调，其次是看大环境。
项目是MIT协议，有志者完全可以继续更新，是否和如何发布、协作都可看情况。

**Comment by Pekary** [comment]
啊，好吧，谢谢。。主要最近发现github.io那个主页访问不了了，以为出问题了， 那Close了

**Comment by listen1** [comment]
感谢issue关心。项目还在继续，只是最近有些忙可能进度有些慢。github的主页无法访问可能是github国内访问的问题。

**Comment by Pekary** [comment]
没事，优秀的项目值得大家去关心。主页的问题和DNS有关，目前正常了~

**Comment by hanshou101** [comment]
谢谢Listen1项目为我们带来的自由享受哈~刚看到通知吓我一跳
