### ISSUE TITLE
Chrome Manifest V3 问题

### ISSUE THREAD

**Issue by Dumeng** [listen1/listen1_chrome_extension#237]
根据新的Google Chrome Extension Manifest标准，由于WebRequest被严格限制，未来改插件可能不再兼容新版本的Chrome
https://docs.google.com/document/d/1nPu6Wy4LWR66EFLeYInl3NzzhHzc-qnk4w4PX-0XMw8/preview#heading=h.t5tc5efl7rfz

**Comment by listen1** [comment]
另一篇介绍文章
https://blog.chromium.org/2019/06/web-request-and-declarative-net-request.html

初衷是保护用户隐私和提高chrome效率，实际大大降低了插件的灵活性。如果用新的替代方案 Declarative Net Request API实际只对屏蔽请求的场景做了完整支持。

持续关注中，应该还在design阶段，后续最终方案不好说。

**Comment by Dumeng** [comment]
MV3 is ready to go
https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/

**Comment by listen1** [comment]
迁移到MV3可能需要调研的一些问题：

1. 旧版chrome版本对MV3的支持度，防止MV3版本影响老版本Chrome用户的使用
2. Firefox和IE Edge对MV3的支持度

**Comment by Dumeng** [comment]
MV2将结束支持
https://developer.chrome.com/blog/mv2-transition/

Firefox将在Q4完成MV3支持的开发，但依旧会和Chrome的有所区别
https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update/

**Comment by listen1** [comment]
google v3 timeline published. This will be done in this issue
https://github.com/listen1/listen1_chrome_extension/issues/721
