### ISSUE TITLE
在精选歌单里打开歌单时，点击歌单的文字打开歌单会一直卡在loading

### ISSUE THREAD

**Issue by lychangyong** [listen1/listen1_chrome_extension#24]
在精选歌单里打开歌单时，点击歌单的文字打开歌单会一直卡在loading，点击歌单图片打开歌单能正常显示歌单

**Comment by listen1** [comment]
可以告诉我听的是哪个平台的哪首歌吗？方便定位问题，谢谢

**Comment by lychangyong** [comment]
@listen1 所有平台的精选歌单，在精选歌单首页打开歌单进入具体歌曲时出现，点击歌单图片下面的文字打开歌单会一直卡在loading，但点击歌单图片打开歌单能正常显示

**Comment by listen1** [comment]
已经修复了bug，谢谢你的反馈
