### ISSUE TITLE
v2.2.0版本有没有网页版

### ISSUE THREAD

**Issue by sft7f** [listen1/listen1_chrome_extension#240]
v2.2.0版本好像不支持html网页，我想将v2.2.0版本部署到服务器上，这样ios就能使用了，顺便问一下， 能不能加一个对百度音乐的支持

**Comment by listen1** [comment]
你好，现有版本都只能支持插件版。早期listen1有一个python的服务器版本 github.com/listen1/listen1，但已经很久没维护了，如果要自己开发可以参考一下思路。
百度音乐的最近可能没有充裕的时间，欢迎贡献PR。感谢支持
