### ISSUE TITLE
咪咕音乐无法正常播放

### ISSUE THREAD

**Issue by jalused** [listen1/listen1_chrome_extension#246]
来自咪咕音乐的歌曲没法播放，点击歌曲标题之后会卡住。刚支持咪咕音乐的时候可以正常播放，不知啥时候就不行了

**Comment by listen1** [comment]
感谢反馈，已经在最新的v2.4.0中修复，请更新

**Comment by lovezczh** [comment]
v2.5.0Chrome插件中咪咕音乐的歌曲没法播放，点击歌曲标题之后会卡住。

**Comment by listen1** [comment]
migu又改接口了，在2.5.1里修改了这个问题，感谢反馈
