### ISSUE TITLE
百度音乐无法加载数据

### ISSUE THREAD

**Issue by LinW0W** [listen1/listen1_chrome_extension#249]
百度音乐一直在加载，貌似是跨域问题，请问一下项目中怎么解决跨域问题的，谢谢！

**Comment by listen1** [comment]
百度音乐还没加入，可能是其他平台。
跨域问题主要通过chrome插件提供的`chrome.webRequest.onBeforeSendHeaders.addListener`接口修改referer完成，具体可参考 https://github.com/listen1/listen1_chrome_extension/blob/master/js/background.js
