### ISSUE TITLE
咪咕音乐听不了了！！！

### ISSUE THREAD

**Issue by jiangqc5656** [listen1/listen1_chrome_extension#255]
咪咕音乐都听不了了，预计大概率是因为地址变了，或者返回数据格式变了
建议开发者把所有网站地址都做成动态配置文件，可以直接挂载到指定地址，每次启动软件，或者网页插件，自动取获取配置文件，从配置文件里面读取地址。
解析方式也可以同样处理，做一个解析字段的映射配置文件，如果数据结构有修改，可以修改配置文件的映射关系就好。
可以每次启动软件，或者在设置里面做一个更新按钮，点击后手动去更新配置文件就好.这样软件就不用每次都要等开发者更新才能用了，除非增加新的功能。
因为我喜欢用软件听音乐，chrome浏览器插件太暂用内存了

**Comment by listen1** [comment]
你好，咪咕音乐已经修复，请更新到2.5.1

你的建议很好，一般商业软件也采取动态配置的方式。以后可能借助github平台实现插件的自动更新，方便用户的使用。
