### ISSUE TITLE
被人上架到chrome商城，还卖钱

### ISSUE THREAD

**Issue by findlayfeng** [listen1/listen1_chrome_extension#262]
https://chrome.google.com/webstore/detail/listen-1/pcahopceikngooaaghccpdcfogechhei?hl=zh-CN

**Comment by mu-yu** [comment]
已帮忙举报……

**Comment by findlayfeng** [comment]
不用举报呀，MIT协议的，卖钱不违反协议，只是没有标注来源，来是吐槽一下，本来就是想去查查有没有上架，结果搜到一个收费的，还贼高

**Comment by guhonghu11** [comment]
没错，差点信了

**Comment by yfdyh000** [comment]
@findlayfeng 没错，但[MIT协议](https://github.com/listen1/listen1_chrome_extension/blob/master/LICENSE)有"License and copyright notice"的条件，所以还是违反了。

**Comment by listen1** [comment]
确实有点黑心了。在此声明，本项目开源免费，发布地址只有github的主页。

PS：解释一下Listen1为何没有在谷歌官方商店发布的原因，不希望项目开发团队受到额外的关注（^_^）。因为Chrome商店需要开发者验证，至少需要credit card信息，所以没有用。

欢迎有chrome商店开发者账号的有识之士把Listen1以免费形式搬运上chrome插件平台。但严重鄙视这种冒充官方账号高额收取费用的行为，请帮忙举报。

**Comment by yfdyh000** [comment]
@listen1 有打算举报，但Google要求版权所有人或代表，担心资格不足致直接作废乃至影响举报进展。建议您也亲自举报一下。
https://chrome.google.com/webstore/report/pcahopceikngooaaghccpdcfogechhei?hl=zh-CN&gl=US - 版权/商标，按其流程，最终在[此表单](https://support.google.com/legal/contact/lr_dmca?product=chromewebstoreextensionsgallery&uraw=&hl=zh-Hans)举报。

**Comment by hanbeikai** [comment]
强烈谴责

**Comment by listen1** [comment]
原始网页已经404，应该是各位努力的结果，google已经下架了该插件。感谢各位！
