### ISSUE TITLE
版权原因无法播放，会停止播放，不会自动跳过

### ISSUE THREAD

**Issue by pretendhigh** [listen1/listen1_chrome_extension#263]
版本Listen1 2.5.1，浏览器 google-chrome-stable-75.0.3770.100-1.x86_64， 系统 centos7
问题描述：遇到“版权原因无法播放”的灰色显示歌曲，停止播放音乐，不会跳过，需要手动切换。
Listen1 2.1.6 也遇到这个问题。不知道是不是我自己的环境问题

**Comment by littlePuppyCN** [comment]
不只你一个人，我也是，现在也没修复这个。

**Comment by listen1** [comment]
此次更新解决了大部分情况下无法播放下一首自动停止的问题
https://github.com/listen1/listen1_chrome_extension/pull/393
