### ISSUE TITLE
建议：希望可以跟进chrome的global-media-controls功能

### ISSUE THREAD

**Issue by toure00** [listen1/listen1_chrome_extension#264]
global-media-controls 是chrome77新增的功能，用来全局控制媒体播放，默认是禁用的，
chrome://flags/#global-media-controls
可以进入这个连接启用，目前listen1只支持暂停播放，希望能把上一曲，下一曲，封面加进来
![image](https://user-images.githubusercontent.com/33457469/65960069-2e986280-e486-11e9-9294-5137cd15e7fd.png)

**Comment by gongjiaji** [comment]
附议
