### ISSUE TITLE
希望增加歌单搜索的功能

### ISSUE THREAD

**Issue by YeaseonZhang** [listen1/listen1_chrome_extension#278]
RT

**Comment by whtiehack** [comment]
自己导入就行了  

![image](https://user-images.githubusercontent.com/12741016/86563489-0995ca80-bf97-11ea-9c13-bc66362bb67d.png)

**Comment by listen1** [comment]
你好，已经在v2.17版本中增加了网易云的歌单搜索，后续将添加更多平台，感谢你的建议
