### ISSUE TITLE
除了咪咕音乐，其他不能听

### ISSUE THREAD

**Issue by xuxia2013** [listen1/listen1_chrome_extension#279]
![image](https://user-images.githubusercontent.com/10276783/71654301-ea11b100-2d6b-11ea-98af-5c4ddba1a0f2.png)

**Comment by RecluseWind** [comment]
我这恰恰相反，除了咪咕其他都能听，咪咕首页推荐歌单无法刷新，但是搜索能用，也能通过搜索播放。
我能判断是咪咕网页的问题，因为我直接访问咪咕首页也是打不开。

**Comment by listen1** [comment]
请更新到最新版本尝试，应该已经修复了
