### ISSUE TITLE
歌词暂停之后再播放会跳动

### ISSUE THREAD

**Issue by davinma** [listen1/listen1_chrome_extension#28]
歌词暂停之后再播放，会转至顶部，然后瞬移到当前的位置

**Comment by listen1** [comment]
possible duplicated #27 正在修复中

**Comment by listen1** [comment]
在最新提交版本修复： https://github.com/listen1/listen1_chrome_extension/commit/eee110bca5e27db8fa2076e94c6a54fa4bbd67a4
谢谢你的反馈
