### ISSUE TITLE
扩展 提示说有问题

### ISSUE THREAD

**Issue by kunpeng9** [listen1/listen1_chrome_extension#288]
我已打开开发者模式 还是提示说有错误
![image](https://user-images.githubusercontent.com/44609485/77842676-ceca0c80-71c7-11ea-95fc-44292c9f39bb.png)
---
![image](https://user-images.githubusercontent.com/44609485/77842652-7bf05500-71c7-11ea-83aa-3849ac44568e.png)
---
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem:". Either the 'unsafe-inline' keyword, a hash ('sha256-4i/UgFRq5GV5/zCG+l3zFewouX2lYeboafDGhFLhxvs='), or a nonce ('nonce-...') is required to enable inline execution.
---
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem:". Either the 'unsafe-inline' keyword, a hash ('sha256-ElK29RD3NLaU5hBAN/K5uzZjOlErtdlryb+CNRZVIPU='), or a nonce ('nonce-...') is required to enable inline execution.
---
pascalprecht.translate.$translateSanitization: No sanitization strategy has been configured. This can have serious security implications. See http://angular-translate.github.io/docs/#/guide/19_security for details.
---
![image](https://user-images.githubusercontent.com/44609485/77842709-2799a500-71c8-11ea-986e-e1c122459726.png)
`<script>if (typeof module === 'object') {window.module = module; module = undefined;}</script>`
---
`<script>if (window.module) module = window.module;</script>`    
---
`a.stack.indexOf(a.message)?"Error: "+a.message+"\n"+a.stack:a.stack:a.sourceURL&&(a=a.message+"\n"+a.sourceURL+":"+a.line));return a}function e(a){var b=d.console||{},e=b[a]||b.log||A;return function(){var a=[];r(arguments,function(b){a.push(c(b))});return Function.prototype.apply.call(e,b,a)}}var f=Aa||/\bEdge\//.test(d.navigator&&d.navigator.userAgent);return{log:e("log"),info:e("info"),warn:e("warn"),error:e("error"),debug:function(){var c=e("debug");return function(){a&&c.apply(b,arguments)}}()}}]}`

**Comment by listen1** [comment]
这个是为了兼容桌面版的代码，应该不影响插件运行
