### ISSUE TITLE
咪咕无法播放

### ISSUE THREAD

**Issue by oxi0w0ixo** [listen1/listen1_chrome_extension#292]
前一天还都正常，突然咪咕全部都播放不了

**Comment by dreamerlyz** [comment]
我也遇到了相同的问题！求解！

**Comment by listen1** [comment]
请升级到v2.6.0版本，修复了咪咕音乐的问题。

**Comment by gvjac** [comment]
> 请升级到v2.6.0版本，修复了咪咕音乐的问题。

请问如何升级到最新版本？

**Comment by listen1** [comment]
Chrome安装

下载项目的zip文件，在项目文件右上方有个 Download ZIP, 解压到本地，或在release页面中下载对应版本号的压缩包。

chrome右上角的设置按钮下找到更多工具，打开扩展程序

选择 加载已解压的扩展程序(如果没有显示先选中开发者模式)，选中解压后的文件夹，完成！

**Comment by v-yunbin** [comment]
![屏幕截图(28)](https://user-images.githubusercontent.com/38179632/107203258-2b2bc880-6a36-11eb-9d00-2b119f6fc72d.png)
那个都不能用。
