### ISSUE TITLE
我注意到英文readme中Firefox的插件链接已经失效

### ISSUE THREAD

**Issue by sonyxu** [listen1/listen1_chrome_extension#293]
新的插件链接如下：
https://addons.mozilla.org/zh-CN/firefox/addon/listen1-from-chrome/versions/?src=search
不知道不是你自己发布的，
并注意到你很久没有更新项目，如果一直没有回复可能会邮件骚扰确认存亡😂

**Comment by caliban511** [comment]
感谢大佬指路。

**Comment by RecluseWind** [comment]
firefox的插件说明里明确说了不是原作者。

**Comment by caliban511** [comment]
> firefox的插件页面说明里明确说了不是原作者。

项目作者的说明里面有火狐扩展，却没有提供下载也没有扩展站的链接，不晓得是怎么回事。

**Comment by RecluseWind** [comment]
> 
> 
> > firefox的插件页面说明里明确说了不是原作者。
> 
> 项目作者的说明里面有火狐扩展，却没有提供下载也没有扩展站的链接，不晓得是怎么回事。

按中文说明自己打包，英文说明没更新而已。

**Comment by sonyxu** [comment]
> firefox的插件页面说明里明确说了不是原作者。

在我提问的时候 发布者的声明中没有说自己不是原作者。现已得知自行关闭话题。
