### ISSUE TITLE
咪咕音乐歌单只能导入前20首，好像不支持分页

### ISSUE THREAD

**Issue by HeLLLLL** [listen1/listen1_chrome_extension#297]
咪咕的歌单里面100多首歌，只能导入前20首，链接里面的page无法识别

**Comment by Soulcrzkc** [comment]
虾米好像也只有30首

**Comment by listen1** [comment]
> 虾米好像也只有30首
虾米的问题已经修复了

**Comment by listen1** [comment]
咪咕歌单分页的问题已经在此次提交中修复
https://github.com/listen1/listen1_chrome_extension/commit/9d313f943342fe7e2b2c8d9b516372d4b1fa35b0
