### ISSUE TITLE
快捷键的支持

### ISSUE THREAD

**Issue by MickeyHub** [listen1/listen1_chrome_extension#3]
希望可以增加快速搜索等快捷键，方便使用

**Comment by xuanll** [comment]
:+1: 同样期待快捷键，上下调整音量等

**Comment by listen1** [comment]
预告：明天发布最新版将支持快捷键功能

**Comment by listen1** [comment]
快捷键功能已经加入，请更新最新版插件：https://github.com/listen1/listen1_chrome_extension/releases
