### ISSUE TITLE
建议：增加非版权音乐对版权音乐的关联

### ISSUE THREAD

**Issue by IOAOl** [listen1/listen1_chrome_extension#300]
一些音乐在别的平台没有版权限制，如果遇到版权问题，提供接口搜索其他平台看是否有无版权版本进行播放

**Comment by listen1** [comment]
很好的建议。已经在play-failover这个分支开发中了

**Comment by listen1** [comment]
V2.9.0增加了自动切换源的选项，可以一试。感谢你的建议。
