### ISSUE TITLE
支持本地音乐导入

### ISSUE THREAD

**Issue by bald-head** [listen1/listen1_chrome_extension#304]
希望以后支持本地音乐播放，这样一直在线播放，很消耗流量。特别是大学生编程在学习上课的时候只能用手机热点的时候，很不方便，我就是一个例子

**Comment by listen1** [comment]
你好，现在的桌面版已经支持本地音乐了，插件版还在调研是否有权限访问本地文件。感谢反馈

**Comment by ldgks** [comment]
> 你好，现在的桌面版已经支持本地音乐了，插件版还在调研是否有权限访问本地文件。感谢反馈

以PWA应用的形式安装，好像可以申请权限访问本地文件，导入歌曲什么的。
