### ISSUE TITLE
能支持后台播放么

### ISSUE THREAD

**Issue by sxyandapp** [listen1/listen1_chrome_extension#307]
能支持后台播放么，可以通过扩展栏的图标查看状态（其实就有点类似桌面播放器了）
（还有点小建议，作者是国人的话，注释啥的能写成中文么，看英文的注释没中文容易理解，本来想对这个插件进行二次开发，一看注释居然都是e文，而且还是angluar写的<本人只稍微懂点react和vue>，完完全全的懵逼啊）

**Comment by listen1** [comment]
已经在最新代码中支持后台播放模式。感谢反馈
