### ISSUE TITLE
单曲循环

### ISSUE THREAD

**Issue by listen1** [listen1/listen1_chrome_extension#31]

**Comment by richdho** [comment]
Hello, 这个功能本身我已经实现了， 就差个单曲循环的图标， 我想问下那个 icon 的class 是什么？ 我试过“icn-repeat” 不行
listen1.html ：
`
<a class="icn" ng-class="{ 'icn-repeat': settings.playmode == 2,'icn-shuffle': settings.playmode == 1, 'icn-loop': settings.playmode == 0 }" title="{{ settings.playmode | playmode_title }}(s)" ng-click="changePlaymode()"></a>
`
解决了这个我就send you a pull request

**Comment by listen1** [comment]
赞，这个图标之前没有做，我做一个就行

**Comment by richdho** [comment]
嗯，连图标都能自己动手，赞！ 我已经 send PR 了， 你看看 #47

**Comment by listen1** [comment]
solved https://github.com/listen1/listen1_chrome_extension/commit/358dab5563fd3485dfba2808ca5eed52644bf97f
