### ISSUE TITLE
跟随 issues/113 

### ISSUE THREAD

**Issue by Misng** [listen1/listen1_chrome_extension#310]
开源软件“爆米花时间”[11]（Popcorn Time）是一个 BT 下载客户端，集成了媒体播放器，可以一边下载一边观看。毋庸讳言，它的主要用途是观看盗版的电影和电视剧。

最近，美国电影协会 MPA 向 GitHub 发了一个 DMCA 通知，声称该软件侵害版权，必须立刻下架，GitHub 就将源码下架了。大多数情况下，这就是故事的结局，但“爆米花时间”不接受这个结局，提交了 DMCA 反通知，认为 MPA 的请求不合法，因为该源码不侵犯 MPA 版权，“该代码是我们100％的劳动成果，不包含任何版权材料，请再次检查，” 开发人员写道。结果，GitHub 恢复了源码的访问权限。

现在还不清楚，美国电影协会将如何反应。这里的问题就是，如果代码不直接侵犯版权，也不直接链接到侵犯版权的材料，而是被用作侵犯版权的用途，那么 DMCA 通是否适用？这些代码是否可以自由传播？

**Comment by listen1** [comment]
感谢留言。DMCA事宜希望都在 #113 讨论。
