### ISSUE TITLE
Firefox版歌词界面的滑动条显示有点问题

### ISSUE THREAD

**Issue by RecluseWind** [listen1/listen1_chrome_extension#313]
插件在firefox 76上用时，滑动条显示有些问题，会显得很难看。
比如这样
![截图](https://user-images.githubusercontent.com/22146920/83474572-e91db080-a4be-11ea-8c58-04893d915446.png)

我尝试修改了common.css的代码。
第752行开始，修改增加了针对firefox 滑动条的代码。

```
page .playsong-detail .detail-songinfo .lyric {
  flex: 0 0 380px;
  overflow-y: scroll;
  color: var(--lyric-default-color);
  scrollbar-width: thin;
  scrollbar-color: var(--scroll-color) var(--content-background-color);
  font-size: 14px;
}
```

**Comment by listen1** [comment]
merged with PR https://github.com/listen1/listen1_chrome_extension/pull/314
