### ISSUE TITLE
网易云音乐网页版现在只能获取歌单前10首歌了

### ISSUE THREAD

**Issue by GeekDuanLian** [listen1/listen1_chrome_extension#316]
登录之后也只能获取前20首，看来是逼着用户去用客户端了
有什么解决方法吗

**Comment by RecluseWind** [comment]
只能找新的API端口或者用第三方的API了。

**Comment by TreasureJade** [comment]
我下载了客户端，然后点了一下链接。重新开了一下listen1，就正常了。不知道是啥原因

**Comment by GeekDuanLian** [comment]
> 我下载了客户端，然后点了一下链接。重新开了一下listen1，就正常了。不知道是啥原因

看一下 Cookie ?

**Comment by GeekDuanLian** [comment]
找到一个曲线救国的方法：
如果是登录状态，且歌单所有者是自己，那么就可以获取到全部歌曲
所以可以先用客户端，把别人歌单的歌曲，全部拖到自己的一个新歌单里，并且设置为私密歌单
然后再去 Listen 1 添加自己歌单的链接，就可以正常获取全部歌曲了
并且也不会有试听 30 秒的情况，如果要 VIP 才能播放的会自动跳过

**Comment by listen1** [comment]
感谢反馈，已经在 `v2.8.0` 中修复

https://github.com/listen1/listen1_chrome_extension/releases/tag/v2.8.0

**Comment by GeekDuanLian** [comment]
> 感谢反馈，已经在 `v2.8.0` 中修复
> 
> https://github.com/listen1/listen1_chrome_extension/releases/tag/v2.8.0

感谢大佬出手，直接源头修复👍
