### ISSUE TITLE
我上传到Firefox上的Listen1附加组件一段时间前被下架

### ISSUE THREAD

**Issue by TNT-c** [listen1/listen1_chrome_extension#325]
我上传到Firefox上的Listen1附加组件一段时间前被下架了，本来已经有200+用户，也收到了几个好评，但是几天前我收到了邮件说被下架

邮件原文如下

Hello,

Due to issues discovered during the review process, your add-on Listen 1 has been disabled on addons.mozilla.org and no longer appears in the gallery. Users who have previously installed your add-on will be able to continue using it.

Please see the reviewer's comments below for more information.

********
Details:
This add-on didn&#39;t pass review because of the following problems:

1) Your add-on includes a JavaScript library file that doesn&#39;t match any versions known to us. We require all add-ons to use unmodified release versions. We require all add-ons to use unmodified release versions.
Please make sure you are using an exact copy of the original maintainers release version. For more information, refer to https://developer.mozilla.org/en-US/Add-ons/Third_Party_Library_Usage
Here are some examples that were discovered:
js/vendor/jquery-3.3.1.min.js

Note: Please do not copy/paste library codes. Please download the library and use without altering.

2) Due to security issues, for the time being, we will only allow the latest version of AngularJS as long as angular is not loaded on a content script.

Reviewer:
Crypto

********

Please address the issues raised in the reviewer's notes and inquire about any unclear items. Afterwards, please upload a new version of your add-on at https://addons.mozilla.org/en-US/developers/addon/listen1-from-chrome/versions.

Thank you for your attention.

********
Developer Resources
********

To respond, please reply to this email or visit: https://addons.mozilla.org/en-US/developers/addon/listen1-from-chrome/versions

You can also get in touch with us using these channels: https://developer.mozilla.org/Add-ons#Contact_us

For tips on how to attract more users by updating your add-on’s listing, please visit: https://developer.mozilla.org/Add-ons/Listing

To learn more about the review process, please visit: https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews

-- 
Mozilla Add-ons Team
https://addons.mozilla.org

===================================================================
You received this email because you're subscribed to:
   * email me when my add-on is reviewed by a reviewer

You can't unsubscribe from this type of email.

Manage email notifications: https://addons.mozilla.org/users/edit#acct-notify

注明：
1.我已经注明这个附加组件不是我制作的，并且附上了GitHub上的地址
2.我没有进行任何收费
3.我对listen1作出了一些细节修改：在i18n/en_US.json,i18n/zh_CN.json,i18n/fr_FR.json中的 "_IMPORTING_PLAYLIST_SUCCESS"改为了 "_IMPORTING_PLAYLIST_SUCCES"（虽然我不知道这是干嘛的，但是不改的话提交时报错，只是我测试的时候好像没什么影响）
4.还改了manifest.json，当然这个不改不行

现在listen1已经被下架，如何让它重新上架？请帮助我
邮箱：488321417@qq.com

**Comment by yfdyh000** [comment]
你的 jquery-3.3.1.min.js 需要与jquery官方发布版本的文件完全一致。

**Comment by RecluseWind** [comment]
我对比了下，其实listen1代码库里的jquery-3.3.1.min.js和jquery官方发布版本就少一个回车。。。。。。
但是这导致两个文件的MD5值不一样，所以被检测出来不一致。

**Comment by TNT-c** [comment]
感谢帮助，已经修复jquery-3.3.1.min.js（但还是希望作者能直接改好啊）现已重新上架，版本为2.9.0
[https://addons.mozilla.org/zh-CN/firefox/addon/listen1-from-chrome/](url)

**Comment by RecluseWind** [comment]
> 
> 
> 感谢帮助，已经修复jquery-3.3.1.min.js（但还是希望作者能直接改好啊）现已重新上架，版本为2.9.0
> [https://addons.mozilla.org/zh-CN/firefox/addon/listen1-from-chrome/](url)

你下次更新不必修改manifest.json，源代码的manifest.json对firefox一样有用，多的commands的代码是快捷键代码，而manifest_firefox里多的就是最上面几行关于最低版本要求，不是太重要，可要可不要。

**Comment by TNT-c** [comment]
但是附加组件ID己经被占用，直接上传会报错，我试过





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "listen1/listen1_chrome_extension"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月9日(星期四) 晚上10:21
收件人:&nbsp;"listen1/listen1_chrome_extension"<listen1_chrome_extension@noreply.github.com&gt;;
抄送:&nbsp;"TNT"<488321417@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [listen1/listen1_chrome_extension] 我上传到Firefox上的Listen1附加组件一段时间前被下架 (#325)





  
感谢帮助，已经修复jquery-3.3.1.min.js（但还是希望作者能直接改好啊）现已重新上架，版本为2.9.0
 https://addons.mozilla.org/zh-CN/firefox/addon/listen1-from-chrome/
  
你下次更新不必修改manifest.json，源代码的manifest.json对firefox一样有用，多的commands的代码是快捷键代码，而manifest_firefox里多的就是最上面几行关于最低版本要求，不是太重要，可要可不要。

**Comment by RecluseWind** [comment]
> 
> 但是附加组件ID己经被占用，直接上传会报错，我试过
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "listen1/listen1_chrome_extension" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月9日(星期四) 晚上10:21 收件人:&nbsp;"listen1/listen1_chrome_extension"<listen1_chrome_extension@noreply.github.com&gt;; 抄送:&nbsp;"TNT"<488321417@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [listen1/listen1_chrome_extension] 我上传到Firefox上的Listen1附加组件一段时间前被下架 (#325) 感谢帮助，已经修复jquery-3.3.1.min.js（但还是希望作者能直接改好啊）现已重新上架，版本为2.9.0 https://addons.mozilla.org/zh-CN/firefox/addon/listen1-from-chrome/ 你下次更新不必修改manifest.json，源代码的manifest.json对firefox一样有用，多的commands的代码是快捷键代码，而manifest_firefox里多的就是最上面几行关于最低版本要求，不是太重要，可要可不要。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

抱歉，我实验firefox不需要commands的代码快捷键也起作用，所以我把回复已经删除了。对于ID冲突，你只需要修改"id": "githublisten1@gmail.com"就行。

**Comment by listen1** [comment]
非常感谢楼主的搬运。之前的firefox一度因为官方限制angular旧版本的审核而下架了，所以listen1的firefox版一直是空缺的状态。有了TNT君的工作，大家终于又可以在firefox平台上使用Listen1了。谢谢。

希望能把一些firefox合规性的修改合并到主线来，方便以后的更新上线。也希望有小伙伴有余力把listen1发布到chrome web store的同学，让chrome用户的更新变的更加简单。

**Comment by TNT-c** [comment]
listen1在addons.mozilla.org又被下架了。。。。。
邮件原文：
Hello,


Due to issues discovered during the review process, your add-on Listen 1 has been disabled on addons.mozilla.org and no longer appears in the gallery. Users who have previously installed your add-on will be able to continue using it.

Please see the reviewer's comments below for more information.

********
Details:
This add-on didn&#39;t pass review because of the following problems:

1) Due to security issues, for the time being, we will only allow the latest version of AngularJS as long as angular is not loaded on a content script.

Reviewer:
Crypto

********

Please address the issues raised in the reviewer's notes and inquire about any unclear items. Afterwards, please upload a new version of your add-on at https://addons.mozilla.org/en-US/developers/addon/listen1-from-chrome/versions.

Thank you for your attention.



********
Developer Resources
********

To respond, please reply to this email or visit: https://addons.mozilla.org/en-US/developers/addon/listen1-from-chrome/versions

You can also get in touch with us using these channels: https://developer.mozilla.org/Add-ons#Contact_us

For tips on how to attract more users by updating your add-on’s listing, please visit: https://developer.mozilla.org/Add-ons/Listing

To learn more about the review process, please visit: https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews

-- 
Mozilla Add-ons Team
https://addons.mozilla.org


===================================================================
You received this email because you're subscribed to:
   * email me when my add-on is reviewed by a reviewer


You can't unsubscribe from this type of email.

Manage email notifications: https://addons.mozilla.org/users/edit#acct-notify

怎么解决啊。。。

**Comment by RecluseWind** [comment]
> 
> 
> listen1在addons.mozilla.org又被下架了。。。。。
> 邮件原文：
> Hello,
> 
> Due to issues discovered during the review process, your add-on Listen 1 has been disabled on addons.mozilla.org and no longer appears in the gallery. Users who have previously installed your add-on will be able to continue using it.
> 
> Please see the reviewer's comments below for more information.
> 
> Details:
> This add-on didn't pass review because of the following problems:
> 
>     1. Due to security issues, for the time being, we will only allow the latest version of AngularJS as long as angular is not loaded on a content script.
> 
> 
> Reviewer:
> Crypto
> 
> Please address the issues raised in the reviewer's notes and inquire about any unclear items. Afterwards, please upload a new version of your add-on at https://addons.mozilla.org/en-US/developers/addon/listen1-from-chrome/versions.
> 
> Thank you for your attention.
> 
> Developer Resources
> 
> To respond, please reply to this email or visit: https://addons.mozilla.org/en-US/developers/addon/listen1-from-chrome/versions
> 
> You can also get in touch with us using these channels: https://developer.mozilla.org/Add-ons#Contact_us
> 
> For tips on how to attract more users by updating your add-on’s listing, please visit: https://developer.mozilla.org/Add-ons/Listing
> 
> To learn more about the review process, please visit: https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews
> 
> --
> Mozilla Add-ons Team
> https://addons.mozilla.org
> 
> ===================================================================
> You received this email because you're subscribed to:
> 
>     * email me when my add-on is reviewed by a reviewer
> 
> 
> You can't unsubscribe from this type of email.
> 
> Manage email notifications: https://addons.mozilla.org/users/edit#acct-notify
> 
> 怎么解决啊。。。

让保证AngularJS和官方最新版一致，这个我就无能为力了。水平不够，不知道替换成最新版后和代码兼容不。

**Comment by RecluseWind** [comment]
> 
> 
> 里面一共有五个Angular开头的javascript文件，我把angular.min.js从1.7.5改成了1.8.0，其他的用不用改？

我也不知道，水平不够，不知道代码会不会冲突。AngularJS官方文件就一个，其他的应该是其他开源作者的。

**Comment by linsui** [comment]
抱歉发在这里，但 Firefox 扩展商店的扩展没有问题跟踪器和存储库。
@TNT-c 请问可以更新扩展到最新版吗？
希望可以将更改合并到主线并由官方继续发布更新，以便及时更新 :joy:

**Comment by TNT-c** [comment]
抱歉有点久没更新，最近开学了有点忙，我会尽量更新，新版本已经上架
但是问题跟踪器和存储库怎么搞我不清楚（我水平真的十分有限），能不能麻烦告诉我一下
Firefox商店上的比官方的只是多了一个标签页图标，不是特别大的改动，我加上去挺快的 
@linsui

**Comment by linsui** [comment]
谢谢！@TNT-c
我想的是如果有些改动，就在 GitHub 上 fork 这个库，然后有相关反馈之类的可以直接在那边提比较方便。:joy: 改动不大的话不如直接合并进主线。然后可以[用 GitHub Action 自动上传](https://github.com/marketplace/actions/firefox-addon-action)。:+1:

**Comment by TNT-c** [comment]
自动上传恐怕不太可以，因为官方的UUID早就被占用了，我每次上传都要改一下

**Comment by linsui** [comment]
这个问题需要请 @listen1 解决。
