### ISSUE TITLE
关于播放失败时自动切换播放源的功能

### ISSUE THREAD

**Issue by PV-NTR** [listen1/listen1_chrome_extension#332]
想了解一下这个功能现在是beta测试版吗，现在我歌单的歌似乎并不能自动切换播放源，2.10.0版的

**Comment by RecluseWind** [comment]
确实是bata版，而且这个功能不是每首歌都能成功的。需要筛选匹配的东西太多，只能说有点用。

**Comment by PV-NTR** [comment]
> 确实是bata版，而且这个功能不是每首歌都能成功的。需要筛选匹配的东西太多，只能说有点用。

好的，谢谢说明~
