### ISSUE TITLE
希望加入“导入歌单”的功能

### ISSUE THREAD

**Issue by hub01** [listen1/listen1_chrome_extension#34]
希望能够从歌单链接，如 http://music.163.com/#/playlist?id=383133426 导入歌单。

**Comment by yoonhakcher** [comment]
同求虾米精选集的导入

**Comment by listen1** [comment]
现已支持导入歌单功能，在我的歌单界面，点击“打开歌单”按钮，粘贴支持平台歌单的URL地址即可收藏，播放

**Comment by MinJunGitHub** [comment]
哇哇哇 太感谢

**Comment by qbmiller** [comment]
最新版粘贴不了??歌单

**Comment by listen1** [comment]
> 最新版粘贴不了??歌单

旧的mac桌面版可能有问题，请更新到2.1.4

**Comment by qbmiller** [comment]
> > 最新版粘贴不了??歌单
> 
> 旧的mac桌面版可能有问题，请更新到2.1.4

mac 10.13.6 ; 一直这样. 更新完也这样...  不仅歌单, 查找输入框也是
