### ISSUE TITLE
音量条BUG

### ISSUE THREAD

**Issue by ciaranchen** [listen1/listen1_chrome_extension#342]
我遇到了与 [listen1_desktop中的一个issue](https://github.com/listen1/listen1_desktop/issues/80) 同样的问题，这个Bug不是出现在desktop的而是在chrome_extension。

`listen1_chrome_extension` 使用了`SoundManager2`的过去版本。它在使用 `u` 和 `d` 调节音量时直接使用了`angularPlayer.adjustVolume`（SoundManager2最新版本已删除此函数），这个函数没有做调整音量后是否超出范围的检查而是直接接将音量改变后的值交给 [SMSSound.setVolume](https://github.com/listen1/listen1_chrome_extension/blob/ecec53017b6fd4b61ab367e5d165c40205c6920f/js/vendor/angular-soundmanager2.js#L2565-L2607)。这个函数在修改IO的音量时，确实调整了范围，但是是直接将修改后的值仍旧是直接赋给了volume变量；这意味着volume的值可能低于0或者超过100。

在`listen1.html`的音量条实现方式是`volume`变量作为音量条的长度，如果低于0则html中的width失效，就会使用默认长度，小圆点跑到右侧。如果超过100则会超出原本的音量条。所以可能需要在使用`u` `d` 调节音量后再次修改`volume`，或者重新实现一个检查范围的adjustVolume。

希望开发者修复。

**Comment by listen1** [comment]
更换了howler，音量问题应该已经解决
