### ISSUE TITLE
导入歌单有一首歌导入错误时，一直 loading

### ISSUE THREAD

**Issue by leadream** [listen1/listen1_chrome_extension#344]
我尝试导入 https://music.163.com/playlist?id=741201222&userid=29733121 这个歌单，但是一直处于 loading 状态，打开控制台发现有一首歌导入失败阻塞了。

![image](https://user-images.githubusercontent.com/12868055/89780105-598e2100-db43-11ea-9591-5f4bf1e0d18e.png)

**Comment by RecluseWind** [comment]
是否是和#331 一样，是云盘的私人音乐？

**Comment by leadream** [comment]
@RecluseWind 不是，这是一个公开歌单： https://music.163.com/playlist?id=741201222

**Comment by RecluseWind** [comment]
才发现这个歌单歌好多，总共有1420首，估计是数据溢出了，控制台报错地方还包括angular.min.js。

**Comment by leadream** [comment]
原来如此，多谢了。我自己先研究下看看。

**Comment by RecluseWind** [comment]
我在网上搜到有个人改了代码修复了这个问题。
网址：https://www.cnblogs.com/NBDWDYS2214143926/p/13384020.html

**Comment by YueShangGuan** [comment]
我已经pr了
