### ISSUE TITLE
添加 favicon

### ISSUE THREAD

**Issue by linsui** [listen1/listen1_chrome_extension#346]
请问是否可以给扩展页面添加一个图标？我使用的使 Firefox 上的第三方扩展。谢谢

**Comment by RecluseWind** [comment]
没有看懂你的意思。哪个页面添加一个图标。

**Comment by linsui** [comment]
扩展播放音乐时的播放器页面。目前标签页标题显示的是播放/暂停图标和当前曲目。
![sshot-010](https://user-images.githubusercontent.com/36977733/90349564-df213d80-e029-11ea-8260-ca80273f29d0.png)
固定标签页后没有图标
![sshot-011](https://user-images.githubusercontent.com/36977733/90349625-0aa42800-e02a-11ea-93ab-89b3af73bbe8.png)
是否可以加上 listen1 的图标或者同样显示播放/暂停图标？

**Comment by RecluseWind** [comment]
chrome版是有图标的，firefox需要在listen1.htm里的<head></head>之间加两行代码：
```
<link rel="shortcut icon" href="images/logo_16.png"/>
<link rel="bookmark" href="images/logo_16.png"/>
```
一个是标签页的图标，一个是书签的图标。
不知道你是用的商店的还是离线的，商店的你需要联系@TNT-c 修改。

**Comment by linsui** [comment]
谢谢！我使用的是 @TNT-c 上传的版本。@TNT-c 请问您是否可以添加上述修改？

**Comment by TNT-c** [comment]
已经添加修改并上传，测试未发现问题 @linsui

**Comment by linsui** [comment]
@TNT-c 谢谢！

**Comment by linsui** [comment]
图标消失了，请修复一下，谢谢 @TNT-c 
请问这个更改可以包含到此仓库中吗？

**Comment by RecluseWind** [comment]
我来提交到仓库里吧，这样就不用每次都麻烦@TNT-c 修改了。

**Comment by linsui** [comment]
谢谢！
