### ISSUE TITLE
底部控制栏歌曲名与按钮重叠

### ISSUE THREAD

**Issue by linsui** [listen1/listen1_chrome_extension#349]
![sshot-013](https://user-images.githubusercontent.com/36977733/90633901-692df980-e216-11ea-9435-4f041287ac3d.png)

缩放页面后歌曲名可能与按钮重叠。

**Comment by RecluseWind** [comment]
这个问题解决倒是好解决，就是歌曲名又要居中又要不重叠就只能左边也空出来，当缩小页面也不大好看。而如果要缩小页面好看就不能居中。

**Comment by linsui** [comment]
或者可以将那两个按钮放到其他位置？
刚刚发现如果继续放大，播放列表中的按钮会泄露出来。

![sshot-004](https://user-images.githubusercontent.com/36977733/90866883-08243400-e384-11ea-8acb-efcc9555905f.png)

**Comment by RecluseWind** [comment]
> 
> 
> 或者可以将那两个按钮放到其他位置？
> 刚刚发现如果继续放大，播放列表中的按钮会泄露出来。
> 
> ![sshot-004](https://user-images.githubusercontent.com/36977733/90866883-08243400-e384-11ea-8acb-efcc9555905f.png)

你是想说继续缩小会出现吧。这问题好解决，右边控制栏加一个“z-index: 1;”就解决了。倒是缩小到出现横向滚动条时，播放列表会被抬起来的问题不好办。
至于改变排版的问题，这个得看作者的意思了。就目前的排版观感我是觉得没必要改，毕竟小页面的用户需求不多吧。

**Comment by linsui** [comment]
我对播放器大小无所谓，主要是为了放大歌词，如果可以单独放大歌词的部分就好了。另一个办法是减少播放按钮和音量条占用的空间。目前固定为 300px，放大页面后会显得比较大。

**Comment by RecluseWind** [comment]
没懂你的意思，歌词不是一个整版吗，还不够大

> 
> 
> 我对播放器大小无所谓，主要是为了放大歌词，如果可以单独放大歌词的部分就好了。另一个办法是减少播放按钮和音量条占用的空间。目前固定为 300px，放大页面后会显得比较大。

没懂你的意思，歌词页面不是一个整版吗，还不够大吗。而且歌词显示和底部控制栏也没关系啊。

**Comment by linsui** [comment]
我是想要放大字体。100% 的缩放是这样的

![sshot-005](https://user-images.githubusercontent.com/36977733/90872655-81c02000-e38c-11ea-897d-98e6c6d5d626.png)

放大后是

![sshot-006](https://user-images.githubusercontent.com/36977733/90872688-8ab0f180-e38c-11ea-9b0e-3b6273d7f7da.png)

**Comment by listen1** [comment]
暂时做了简单的修复，预留了右侧按钮的位置。
