### ISSUE TITLE
无法打开酷我歌单

### ISSUE THREAD

**Issue by sdoit** [listen1/listen1_chrome_extension#351]
应该是酷我官网更改了歌单链接的格式，更改正则表达式以修复问题

将`\provider\kuwo.js`中的`function kw_parse_url(url) `   446行:
`const match = /\/\/www.kuwo.cn\/playlist\/index\?pid=([0-9]+)/.exec(url);` 
修改为
`const match = /\/\/www.kuwo.cn\/playlist_detail\/([0-9]+)/.exec(url);`
即可解决问题。

即：

```
function kw_parse_url(url) {
    let result;
    // const match = /\/\/www.kuwo.cn\/playlist\/index\?pid=([0-9]+)/.exec(url);
    const match = /\/\/www.kuwo.cn\/playlist_detail\/([0-9]+)/.exec(url);
    if (match != null) {
      const playlist_id = match[1];
      result = {
        type: 'playlist',
        id: `kwplaylist_${playlist_id}`,
      };
    }
    return result;
  }
```

**Comment by listen1** [comment]
非常感谢反馈，已经在https://github.com/listen1/listen1_chrome_extension/commit/d0c48c40a9b2750b5d6d4e812d4357d2fd382456 这个commit中修复
