### ISSUE TITLE
QQ音乐歌单导入失败

### ISSUE THREAD

**Issue by FlyingGoldenFish** [listen1/listen1_chrome_extension#357]
显示未能打开输入的歌单地址

**Comment by listen1** [comment]
谢谢你的反馈，方便的话能否粘贴一下无法打开的歌单链接地址?

**Comment by FlyingGoldenFish** [comment]
https://c.y.qq.com/base/fcgi-bin/u?__=1MsbSLu

**Comment by listen1** [comment]
原因是现有获取歌单原始id的方法主要是从url中获得id，但未考虑短链后跳转的情况，将在后续修复

**Comment by listen1** [comment]
fixed in https://github.com/listen1/listen1_chrome_extension/commit/baf3c89c2b47a58f0ca0e6af10b7c45ce3218e2c
