### ISSUE TITLE
Mac版可以支持键盘自带的上一曲、下一曲按键吗？

### ISSUE THREAD

**Issue by wflaowei** [listen1/listen1_chrome_extension#358]
如题，在mac下，网易云音乐等APP，无论是妙控蓝牙键盘，还是普通多媒体键盘，都可以上一曲下一曲，而listen1不可以。

我觉得如果支持多媒体键盘的上一曲下一曲按键，无论是在win还是mac下都应该可以用这些按键。

**Comment by listen1** [comment]
好的，将把这个issue提到桌面版的项目中
