### ISSUE TITLE
bilibili的音乐无法播放

### ISSUE THREAD

**Issue by zhengfan2014** [listen1/listen1_chrome_extension#363]
查看f12，是在
https://upos-sz-mirrorks3.bilivideo.com/ugaxcode/19613ace937082bd4572d04f682b899b-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1602926824&gen=playurl&os=ks3bv&oi=1948230576&trid=41c2d113b0284881b32a8740b151acbfB&platform=pc&upsig=32dcf1bf0393a2c0ce3f8af95d14f17d&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&orderid=0,1&logo=00000000
获取m4a文件时被403拒绝访问

**Comment by listen1** [comment]
感谢反馈，已经在代码中修复 https://github.com/listen1/listen1_chrome_extension/pull/364 ，应该不久会发布到最新版中
