### ISSUE TITLE
刚刚在AMO上批量更新，但是2.15.0版本刚上传就被停用了

### ISSUE THREAD

**Issue by TNT-c** [listen1/listen1_chrome_extension#373]
刚刚在把Firefox商店的listen1更新版本，上传的有点急，2.15.0没审核好就传了2.16.0，然后发现2.15.0被停用了，连个理由都没有，咋办
https://img10.360buyimg.com/ddimg/jfs/t1/120494/24/16876/280017/5f9cee6aE2ea3258a/4410a45432ecdf1c.jpg

**Comment by TNT-c** [comment]
审核历史空白
https://img14.360buyimg.com/ddimg/jfs/t1/151015/36/4917/193492/5f9ceed1E534b083c/bb50ed5a8b57b15a.jpg

**Comment by yfdyh000** [comment]
印象中这是正常的，审核压力大，只审核最新版本。

**Comment by listen1** [comment]
已经看到2.17.0版本发布了，赞
