### ISSUE TITLE
更新angular.min.js和jquery至最新版本

### ISSUE THREAD

**Issue by TNT-c** [listen1/listen1_chrome_extension#374]
建议更新angular.min.js脚本，不然在Firefox商店上很容易因安全问题下架
jquery脚本和官方文件不一致（多了一行回车），也成为listen1的早期版本在Firefox商店下架原因之一
如果有哪次更新这两个脚本我忘了改（比如2.14.0-2.17.0的更新），就很有可能会导致下架
已经上传了改过的新版本

**Comment by listen1** [comment]
已更新 angularjs https://github.com/listen1/listen1_chrome_extension/commit/e12194f217d84e2079cad954c5ea204ba15068fa
jquery文件下载后未见差异，是否已经修复过。
