### ISSUE TITLE
edge自动删listen1？？？

### ISSUE THREAD

**Issue by 1406708216** [listen1/listen1_chrome_extension#375]
edge装好listen1可以用，但是第二天扩展插件里就没有listen1了。。。

是用 加载解压缩的扩展 安装进edge里的，出现过 "禁用开发人员模式扩展" 弹窗，被删后插件列表里没有listen1，安装路径里解压的文件夹也没了。

大家的被删过吗？能解决吗？

**Comment by dhxh** [comment]
edge 商店有listen1

**Comment by listen1** [comment]
可以在官方商店搜索listen1安装
