### ISSUE TITLE
listen1 插件ID每次打开都不一样？

### ISSUE THREAD

**Issue by 1406708216** [listen1/listen1_chrome_extension#376]
是用 加载解压缩的扩展 安装进edge里的，但是经常被删。

打包成crx不被删，但是提示“此扩展不是来自任何已知来源，可能是在你不知情的情况下添加的。”被禁用了，完全打不开。

**Comment by RecluseWind** [comment]
打包crx时记得保存pem文件，每次打包都导入id就不会变了。
