### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by charlieslx** [listen1/listen1_chrome_extension#379]
最近无法播放网易的vip音乐

**Comment by listen1** [comment]
你好，当无法播放相关歌曲时，listen1会到其它平台查询相关歌曲的播放资源。

因为平台的版权经常变动，可能导致某些歌曲之前有可用的播放源，后来又不可用了。现在默认是搜索qq，酷我，咪咕的源。

后续我们也会考虑优化这块功能的体验。尽可能的找到可用的源提供给用户。谢谢。
