### ISSUE TITLE
infinite scrolling导致切换精选歌单后可能出现排版混乱

### ISSUE THREAD

**Issue by listen1** [listen1/listen1_chrome_extension#38]

**Comment by wild-flame** [comment]
这个bug我也发现了。。但是不知道什么情况下会出现这种情况~~有时候又没有问题...

**Comment by listen1** [comment]
solved in https://github.com/listen1/listen1_chrome_extension/commit/b9b530b488c7ce4b2dad38c41cfc71539ac44adc

**Comment by listen1** [comment]
@wild-flame 刚开始测的时候是随机重现的，定位到问题可能和infinite-scrolling库有关后，自己实现了一个简单的代替了那个库。看了那个库的源码感觉trick的成分比较大，遇到div内scroll的场景可能会有问题。

**Comment by listen1** [comment]
应该是bootstrap css导致的按钮行为异常，我晚上再commit一下

**Comment by listen1** [comment]
solved https://github.com/listen1/listen1_chrome_extension/commit/29d7466e5a7525b154d2d7849ce0846dcf7b7c33
