### ISSUE TITLE
chrome插件报错

### ISSUE THREAD

**Issue by yogggithub** [listen1/listen1_chrome_extension#381]
从google store下载的chrome插件版，播放报错
chrome: 87.0.4280.66 (Official Build) (64-bit)
Listen1: 2.17.0

extension errors信息如下：
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem:". Either the 'unsafe-inline' keyword, a hash ('sha256-4i/UgFRq5GV5/zCG+l3zFewouX2lYeboafDGhFLhxvs='), or a nonce ('nonce-...') is required to enable inline execution.
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem:". Either the 'unsafe-inline' keyword, a hash ('sha256-ElK29RD3NLaU5hBAN/K5uzZjOlErtdlryb+CNRZVIPU='), or a nonce ('nonce-...') is required to enable inline execution.
pascalprecht.translate.$translateSanitization: No sanitization strategy has been configured. This can have serious security implications. See http://angular-translate.github.io/docs/#/guide/19_security for details.
TypeError: Cannot read property 'title' of null
Uncaught (in promise) NotSupportedError: Failed to load because no supported source was found.
TypeError: Cannot read property 'map' of undefined Possibly unhandled rejection: {}

**Comment by listen1** [comment]
感谢反馈。部分错误是为了兼容桌面版，属于正常信息。不知道功能上有没有问题

**Comment by yogggithub** [comment]
有一些奇怪的问题，但我不确定原因。
比如，播放卡住并直接终止的问题。
一首歌如果卡住，播放就终止了，必须点击下一首切歌并点击开始播放才能继续
切到下一首播放后，再切回到上一首，播放界面显示的信息也会卡在下一首不能切换。同理，如果下一首卡住，播放信息会一直显示已播完的歌。
当然，卡住的问题可能是网络原因。也没有版权限制或者其他的提示。

**Comment by listen1** [comment]
这个问题我们已经确认存在了，遇到一些版权受限歌曲无法自动播放的问题，可能是加入自动寻找播放源后没有考虑到多个播放源都失败以后的错误处理。这个问题还在修复中，将尽快更新。

**Comment by yogggithub** [comment]
辛苦了，谢谢
