### ISSUE TITLE
网易云APP的歌单链接无法加载，

### ISSUE THREAD

**Issue by nicklxz** [listen1/listen1_chrome_extension#389]
我用的是chrome插件版， 以下是链接，
http://music.163.com/playlist/600007748/420312899/?userid=420312899 (来自@网易云音乐)

咪咕的也加载不了，一直在那转圈圈
分享 | http://c.migu.cn/0069zb?ifrom=c055e921410db86c6e79cdfd358fb1a2（@咪咕音乐）

**Comment by RecluseWind** [comment]
> 
> 
> 我用的是chrome插件版， 以下是链接，
> http://music.163.com/playlist/600007748/420312899/?userid=420312899 (来自@网易云音乐)
> 
> 咪咕的也加载不了，一直在那转圈圈
> 分享 | [http://c.migu.cn/0069zb?ifrom=c055e921410db86c6e79cdfd358fb1a2（@咪咕音乐）](http://c.migu.cn/0069zb?ifrom=c055e921410db86c6e79cdfd358fb1a2%EF%BC%88@%E5%92%AA%E5%92%95%E9%9F%B3%E4%B9%90%EF%BC%89)

你的咪咕链接不是歌单链接，是歌曲链接
