### ISSUE TITLE
可否部署到docker？

### ISSUE THREAD

**Issue by colourfult** [listen1/listen1_chrome_extension#392]

**Comment by listen1** [comment]
docker主要用于部署服务器类的应用，不知道Chrome插件的使用场景是？

**Comment by yfdyh000** [comment]
他可能指自建网页服务器，访问即可使用，类似桌面应用，但运行在远端。

**Comment by listen1** [comment]
其实Listen1刚开始是一个服务器版本 https://github.com/listen1/listen1，可以参考一下，不过很多音乐平台相关的代码没有更新了

**Comment by a76yyyy** [comment]
> 其实Listen1刚开始是一个服务器版本 [https://github.com/listen1/listen1，可以参考一下，不过很多音乐平台相关的代码没有更新了](https://github.com/listen1/listen1%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%8F%82%E8%80%83%E4%B8%80%E4%B8%8B%EF%BC%8C%E4%B8%8D%E8%BF%87%E5%BE%88%E5%A4%9A%E9%9F%B3%E4%B9%90%E5%B9%B3%E5%8F%B0%E7%9B%B8%E5%85%B3%E7%9A%84%E4%BB%A3%E7%A0%81%E6%B2%A1%E6%9C%89%E6%9B%B4%E6%96%B0%E4%BA%86)

请问这个插件版或者mobile版可以构建成webapp的形式么？可以的话直接用`npm run build`就可以部署到服务器或者docker上实现网页版访问了
