### ISSUE TITLE
自动切换源 添加虾米音乐

### ISSUE THREAD

**Issue by cmmdwl** [listen1/listen1_chrome_extension#396]
添加虾米音乐作为可换源.

**Comment by RecluseWind** [comment]
其实说明写得很清楚，“从酷我，QQ和咪咕音乐搜索”，虾米不在切换源的选择内。

**Comment by RecluseWind** [comment]
呃，没必要关闭Issue啊。。。可以提建议的扩大选择源的啊。

**Comment by cmmdwl** [comment]
> 呃，没必要关闭Issue啊。。。可以提建议的扩大选择源的啊。

好像也是,扩大也不错

**Comment by Dumeng** [comment]
虾米音乐已经于2021年2月5日结束支持
https://h5.xiami.com/app/xiami-frontend/xm-announcement/index/index.html
