### ISSUE TITLE
唯独自己歌单里面的歌播放不了

### ISSUE THREAD

**Issue by danyow** [listen1/listen1_chrome_extension#398]

**Comment by danyow** [comment]
精选里面的歌单就没问题 可以播放

**Comment by listen1** [comment]
抱歉v2.17.2版本有个bug会导致无法播放之前创建对歌单，已经在v2.17.4中修复了此问题，等待chrome商店审核更新就可以了。

**Comment by danyow** [comment]
刚刚下了2.17.4 确实好了 没注意看更新时间 不好意思哈~
