### ISSUE TITLE
支持下firefox？

### ISSUE THREAD

**Issue by WangQiru** [listen1/listen1_chrome_extension#4]

**Comment by vxxholic** [comment]
同求

**Comment by listen1** [comment]
感谢fulesdle，已经合并到主线，
xpi下载地址：[https://github.com/listen1/listen1_chrome_extension/releases/download/v1.1/listen1_firefox_extension_v110.xpi](https://github.com/listen1/listen1_chrome_extension/releases/download/v1.1/listen1_firefox_extension_v110.xpi)

**Comment by vxxholic** [comment]
重启Firefox以后歌单数据丢失

 Listen 1 版本 1.1

火狐中国版42.0

**Comment by listen1** [comment]
firefox插件版可以在项目主页下载： http://listen1.github.io/listen1

**Comment by listen1** [comment]
火狐官方插件地址 https://addons.mozilla.org/zh-CN/firefox/addon/listen-1/
