### ISSUE TITLE
用twitter频繁被登出

### ISSUE THREAD

**Issue by dittlevvee** [listen1/listen1_chrome_extension#40]
用的是chrome浏览器
进入twitter页面后提示Could not authenticate you.然后账号被强制登出
然后停用了您的插件
还是会提示
最后从扩展程序中删除了，恢复正常了

**Comment by listen1** [comment]
感谢您的反馈。可能还需要您的进一步信息。
请问还使用了其他插件吗？插件没有访问twitter的权限。
插件版本是最新的吗？

**Comment by listen1** [comment]
已经修复
