### ISSUE TITLE
收藏歌单消失，创建的歌单无法播放

### ISSUE THREAD

**Issue by Puel1774** [listen1/listen1_chrome_extension#401]
Chrome 版本：Version 87.0.4280.88 (Official Build) (x86_64)
Listen 1 插件版本： 2.17.6 
---
前几天开始创建的歌单就无法播放了，播放进度一直00:00，不知道有没有在加载；但是收藏的歌单能正常播放。而且如果点进创建的歌单里的单首歌的专辑也是能播放的。
刚才打开发现收藏的歌单全部消失……（我也没清过缓存什么的，不知道是什么bug…

**Comment by listen1** [comment]
抱歉最近版本bug有点多，请升级到v2.17.7会解决相关问题
