### ISSUE TITLE
增加后台播放功能，在插件弹出窗口增加播放控制功能

### ISSUE THREAD

**Issue by listen1** [listen1/listen1_chrome_extension#403]
我使用的edge Listen1扩展程序，能不能在listen1网页关闭之后，只要edge浏览器还开着，音乐还能播放，谢谢。
![image](https://user-images.githubusercontent.com/18599108/103432427-9c978080-4c19-11eb-8017-c8cf476a9847.png)

来源：邮件

**Comment by Dumeng** [comment]
需要将SoundManager 2替换掉，使用一个JS Native Music Player以将播放功能移动至后台线程中
https://developer.chrome.com/docs/extensions/mv3/architecture-overview/#background_script
使用Message Passing在Extension Page/Popup Page和后台线程之间进行指令交换
https://developer.chrome.com/docs/extensions/mv3/messaging/

**Comment by listen1** [comment]
有个UI设计交互的问题是，点击菜单栏的按钮后，popup的播放控制和完整模式的播放页面如何选择

**Comment by Dumeng** [comment]
独立的popup controller可以考虑
或者使用Media Session特性启用Global Media Control作为过渡方案
#264 #350
