### ISSUE TITLE
在播放酷狗的音源时，大部分专辑封面和歌词缺失

### ISSUE THREAD

**Issue by listen1** [listen1/listen1_chrome_extension#417]
在播放酷狗的音源时，大部分专辑封面和歌词缺失

来源：邮件

**Comment by RecluseWind** [comment]
最近我正在整理修改这一部分代码，咪咕的代码已经完成，酷狗也基本完成（只有翻译歌词比较麻烦，而且过程复杂，但是其实没多少歌有翻译，在考虑要不要加上翻译歌词）。
但是因为最近似乎在替换axios，所以没有立刻上传，打算等替换完成后再修改合并代码。

**Comment by Dumeng** [comment]
可以先pr的，axios的review还要一段时间，之后再在这边merge就好

**Comment by listen1** [comment]
歌词部分的问题在 26586ac970a17fc35a3ab9ae03b96610d37e655b 中修复。而封面缺失问题仍然存在。

**Comment by RecluseWind** [comment]
我最近找到一个api，可以像网易的一样批量返回歌曲的信息，就是里面的key值获取方法还没找到，虽然目前来看后端还没开始验证key值，随机取值都行。
这个api有一点不好，需要批量的歌曲hash数组，因此前提还是要请求几次数据得到全部hash值，当然比目前每一首都请求一次来说，好多了。

**Comment by RecluseWind** [comment]
还有一个办法，酷狗有一个获取播放链接的api会同时返回封面还有歌词的信息。如果能将获得封面和歌词数据传出去，其实很节约资源。

**Comment by listen1** [comment]
> 还有一个办法，酷狗有一个获取播放链接的api会同时返回封面还有歌词的信息。如果能将获得封面和歌词数据传出去，其实很节约资源。
> 啊，就是修复歌词这个api，能同时得到播放链接，封面和歌词。除了翻译歌词（这是另一个坑了）都有了。
> api可以精简为[https://wwwapi.kugou.com/yy/index.php?r=play/getdata&hash=${song_id}&album_id=${album_id}](https://wwwapi.kugou.com/yy/index.php?r=play/getdata&hash=$%7Bsong_id%7D&album_id=$%7Balbum_id%7D)
 
我也尝试过精简，但是在桌面版里如果不加callback参数就会导致lyrics字段缺失。所以就加上了。具体原因还没查清楚。有一些库桌面版和插件版里的表现确实不太一致。

如果这个链接能获取完整信息，倒可以考虑利用这个信息更新封面信息。/lyric这个接口后续可能考虑作为播放时获取歌曲详细信息的接口，名字可能改一下叫/song_detail之类的，而封面信息这种不影响用户分辨歌曲的信息不强制作为playlist返回结果需要获取到的字段。

**Comment by RecluseWind** [comment]
桌面版差异这么大么😱看来以后要注意这方面的问题，不过我不会搭建桌面版的测试环境😥

> 
> 
> > 还有一个办法，酷狗有一个获取播放链接的api会同时返回封面还有歌词的信息。如果能将获得封面和歌词数据传出去，其实很节约资源。
> > 啊，就是修复歌词这个api，能同时得到播放链接，封面和歌词。除了翻译歌词（这是另一个坑了）都有了。
> > api可以精简为[https://wwwapi.kugou.com/yy/index.php?r=play/getdata&hash=${song_id}&album_id=${album_id}](https://wwwapi.kugou.com/yy/index.php?r=play/getdata&hash=$%7Bsong_id%7D&album_id=$%7Balbum_id%7D)
> 
> 我也尝试过精简，但是在桌面版里如果不加callback参数就会导致lyrics字段缺失。所以就加上了。具体原因还没查清楚。有一些库桌面版和插件版里的表现确实不太一致。
> 
> 如果这个链接能获取完整信息，倒可以考虑利用这个信息更新封面信息。/lyric这个接口后续可能考虑作为播放时获取歌曲详细信息的接口，名字可能改一下叫/song_detail之类的，而封面信息这种不影响用户分辨歌曲的信息不强制作为playlist返回结果需要获取到的字段。

桌面版差异这么大么😱看来以后要注意这方面的问题。不过我不会搭建桌面版的测试环境😥

**Comment by listen1** [comment]
https://github.com/listen1/listen1_chrome_extension/commit/b54dbcf21516e44cdbd10e0eb0c763f936556172
修复了歌曲封面的相关问题
