### ISSUE TITLE
Listen1下一阶段开发的建议

### ISSUE THREAD

**Issue by Dumeng** [listen1/listen1_chrome_extension#419]
Listen 1 基于AngularJS进行开发，在过去的一段时间中一直表现良好。
但是随着时代变换，技术发展最近发现现在AngularJS存在一些严重的问题，例如空载时的CPU高负载以及创建大量的低效DOM。
![image](https://user-images.githubusercontent.com/5249513/104122414-d423cc80-537f-11eb-94f3-58692996f0bb.png)

同时，Google官方已经宣布在本年度（2021）内完全结束对于AngularJS的支持。
[AngularJS End of Lifecycle](https://code.angularjs.org/snapshot/docs/misc/version-support-status)

因此，我个人认为Listen1也时候进入下一阶段的开发了。该项目应该迁移到一个更加现代的前端框架。例如Angular，Vue或者React。

此外，我有些基本的迁移路线图想和大家一起分享。

1. 代码清理，使用工具格式化代码，统一代码风格。移除冗余和废弃代码。优化代码结构，清除不必要的回调和跨模块调用。
2. 更新播放器组件，用新的播放器替换当前的ngSM2。并将播放器放置于独立线程中，从前端对象中分离。
3. 分离底层逻辑，将于UI无关的代码分离出来放入独立线程中，例如LastFM和GitHub的集成，以及最重要的音乐平台集成代码。
4. 更新依赖库，移除老旧和废弃的依赖库，统一不同组件的依赖库。例如移除不需要的加密算法库和JQuery。
5. 添加新的依赖库，以替换原本依赖于AngularJS的部分功能，如使用Axios实现HTTP请求，以替换$Http。
6. 替换AngularJS。此时AngularJS应当只剩下模板渲染的功能，可以在保留HTML结构和CSS样式的情况下进行较为简单的框架替换。

**Comment by listen1** [comment]
非常中肯的建议。Listen1出现时当时angularjs还是主流框架，现在确实需要开始”脱离angularjs化“

1. 代码清理：这个可以首先做。我已经开始使用@Dumeng的eslint新版本开始做原来代码的修复。历史留下的不规范的代码较多，暂时会将大部分违反eslint的规则都先忽略，然后逐步打开规则，修改代码中的错误。

2. 感谢@Dumeng近期开始了从SoundManager2到Howler.js的迁移工作，基本可以运行了。但是Howler有个小问题是没有支持timeupdate的通知，源码采用了requestAnimationFrame的方案，这个可能还需要评估一下，如果对性能影响不大就没关系。

3. loweb模块本身设计的目的就是分离网络请求API，应该可以考虑封装为未来音乐平台接口。LastFM和Github的集成这个确实需要好好考虑一下，有没有可能设计一套插件化的方式对外开发sdk来允许加载基于插件plugin的功能。

4. jQuery移除可以作为近期更新计划。加密算法库可能考虑和框架升级同步进行。详见6

5. 依赖库的问题也可以和6同时进行。其实现在的http模块算是框架提供的一个模块

6. 这是个比较重要的问题。也是工作量相对最大的。

我们考虑从V3.x开始使用现在主流的框架，但是迁移涉及的过程比较复杂。可能首先我们会把原来项目在angularjs的基础上尽可能多的做好模块化让它接近现在以框架开发为主的形态。这块还需要更多的调研。可能先尝试用vue开发一个简单的demo来验证迁移需要注意的问题。到时候，可能在3.x的branch上开始做新版本的迁移开发。但2.x和3.x应该会同时存在一定但时间，毕竟v3.x需要迁移的功能比较繁杂，还涉及到桌面版和插件版的兼容性的一系列测试。

**Comment by CG-man** [comment]
希望作者可以开发一个终端版本, 很喜欢另一个作者的[网抑云命令行版](https://github.com/darknessomi/musicbox), 作为一个码农摸鱼经常开gui总是不太好的, 或者说我要是有精力的话可以直接copy作者你的provider下面的js来进行命令行版本的开发吗? 我会注明原作者.

**Comment by listen1** [comment]
> 希望作者可以开发一个终端版本, 很喜欢另一个作者的[网抑云命令行版](https://github.com/darknessomi/musicbox), 作为一个码农摸鱼经常开gui总是不太好的, 或者说我要是有精力的话可以直接copy作者你的provider下面的js来进行命令行版本的开发吗? 我会注明原作者.

很棒的想法，期待终端版的多平台听歌软件。如果需要这个项目的代码完全没问题，MIT开源协议本身就是开放的。

**Comment by RichardZhang4** [comment]
能不能全局倍速呢？无级调节的那种

**Comment by Dumeng** [comment]
当前已经基本分离了依赖于Angular逻辑层代码。文件结构也已经分离为单个组件单个文件。

接下来可以创建一个新的分支来进行vue3迁移的原型构建。为了让迁移更加平滑，可以在angular应用依然存在的情况下创建一个Vue应用，选择一个无依赖的组件使用Vue重构。例如PlayListController

**Comment by Dumeng** [comment]
#547
简单验证了单组件迁移的方法，希望各位贡献者可以提出一些改进意见

**Comment by wangbiwang** [comment]
希望重构版本可以新增第三方登录系统，记录用户的个人偏好设置、歌单等
个人实现想法：
1. 集成调用Github登录API、Google登录API或者其他第三方平台 接入用户，搞定登录部分。

2.  基于各第三方平台登录后返回的信息， 可以使用各云服务厂商的免费云对象存储，来实现用户个人偏好设置、歌单的云记录。

**Comment by sonichy** [comment]
我是一个拒绝使用框架的人，jQuery都拒绝，我看重原生的寿命和学习成本。

**Comment by listen1** [comment]
关于V3的技术选择，基本确定了Vue3的方案，可以在 #564 中查看具体方案选择和原因

**Comment by listen1** [comment]
V3版本的开发分支： https://github.com/listen1/listen1_chrome_extension/tree/next
