### ISSUE TITLE
批量替换虾米音乐

### ISSUE THREAD

**Issue by Dumeng** [listen1/listen1_chrome_extension#428]
很快虾米音乐就将停止服务，估计歌单会大面积变灰，希望可以有某种方式可以批量替换。

另外，估计搜索和歌单接口也会大量报错。可以考虑移除虾米相关的组件

**Comment by listen1** [comment]
现有的自动选择播放源应该能解决创建歌单中虾米音乐的播放问题。这个还需要确认一下。

计划在官方停止服务后尽快更新。
