### ISSUE TITLE
支持关闭窗口时停止播放

### ISSUE THREAD

**Issue by listen1** [listen1/listen1_chrome_extension#438]
现在默认模式是关闭窗口时，背景页播放器仍然持续播放。比较好的做法可能是在关闭时提示用户可以设置关闭时行为，并默认关闭窗口时停止播放音乐。

这样做的目的： 更大的灵活性。窗口关闭行为本身可能因用户使用习惯而异。

**Comment by Dumeng** [comment]
![image](https://user-images.githubusercontent.com/5249513/105634351-8c7d6480-5e98-11eb-9786-7abe2ce1c9b0.png)
现在可以使用Global Media Control特性在任意位置控制播放。由于获取播放URI的逻辑还存在于loWeb里，未能移动到后台，暂时还不能前后变更播放歌曲，稍后将会添加。

**Comment by listen1** [comment]
Global Media Control的界面真的很好看，也能实现控制功能，很期待加入变更播放歌曲的功能。

Global Media Control的缺点就是用户不太方便找到入口。所以为了照顾大多数用户的使用习惯，后续还是把关闭后后台播放模式作为可选项提供给用户。

**Comment by listen1** [comment]
支持用户选择关闭窗口时行为的PR #448
