### ISSUE TITLE
浏览器media control和extension自带控件交互问题

### ISSUE THREAD

**Issue by mikelxk** [listen1/listen1_chrome_extension#444]
- 在暂停时，如果使用浏览器的media control来控制播放/暂停,会导致extension自带的控件行为和期望的不一致。按钮不会变，进度栏也是暂停的。
- extension的播放/暂停键不能随着media control的播放/暂停而变化。
- 另 似乎 `是否显示专辑封面作为正在播放背景`这个选项无效了。怎么样都无法将封面作为播放背景 fixed in #445

**Comment by listen1** [comment]
尝试简单修复了一下
https://github.com/listen1/listen1_chrome_extension/commit/506d0852173caad8db8628620114ff70c8a54a24

mediasession API的处理函数未指定回调时调用的默认控制未发送后端的状态，这个还在研究具体是通过什么机制控制音频的。加上指定回调函数就可以避免此问题

**Comment by mikelxk** [comment]
Thanks for the fix!
