### ISSUE TITLE
损坏的图片

### ISSUE THREAD

**Issue by Dumeng** [listen1/listen1_chrome_extension#451]
https://github.com/listen1/listen1_chrome_extension/blob/master/images/feather-sprite.svg

好像项目中有引用到一个损坏的图片，可能引起性能问题。

![image](https://user-images.githubusercontent.com/5249513/106105308-c099a380-617e-11eb-8002-4651574843c5.png)

**Comment by listen1** [comment]
在 https://github.com/listen1/listen1_chrome_extension/commit/4360090c722cb016a3be72f07fead77c81413c46 中修复此问题。

原因不明，在svg标签中使用xlink方式引用时浏览器会多次加载该资源。将svg资源直接搬到html文件中时就好了。

**Comment by Dumeng** [comment]
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href

看起来`xlink:href`已经废弃了

**Comment by listen1** [comment]
感谢建议，已经把xlink:href改成href了
