### ISSUE TITLE
Can not add songs to playlist

### ISSUE THREAD

**Issue by mikelxk** [listen1/listen1_chrome_extension#456]
Can not add songs to playlist. That bug both occur in the newest desktop and browser ver.

**Comment by listen1** [comment]
that's the reason why new version is not released. I think still need time to handle these bugs. 

Could you add more details about the bug? Like console error log, network tab info.

**Comment by mikelxk** [comment]
I tried to add the song during search, and while the green notice panel
showed up, the songs never end up getting into the playlist.

Listen 1 <notifications@github.com> 于 2021年1月31日周日 上午7:50写道：

**Comment by listen1** [comment]
fix this in https://github.com/listen1/listen1_chrome_extension/commit/449859efe0005928fcebb8b7ba91417827d58df2 

the reason is axios will automaticly parse json response, but old angularjs http lib leaves it to user.

**Comment by mikelxk** [comment]
Thanks for your commit  👍
