### ISSUE TITLE
打开网易云音乐歌单，一直loading

### ISSUE THREAD

**Issue by listen1** [listen1/listen1_chrome_extension#457]
bug 表现：
打开歌单时一直loading状态。查看console.log可见相关报错是返回数据读取字段缺失。正常返回json，发生这种情况时返回空字符串，但是status code还是200

可能原因：
网易云接口返回不稳定，不排除因为请求字段和正常客户端的差异导致的服务器限制。

或也可能因为更换axios后的底层改变造成。

**Comment by Dumeng** [comment]
能否提供一个有问题的歌单ID

**Comment by listen1** [comment]
> 能否提供一个有问题的歌单ID

和具体歌单无关。同一个歌单反复打开有概率刷不出来了。可以在网易云的精选歌单里随便找一个试试
