### ISSUE TITLE
添加了繁体中文翻译

### ISSUE THREAD

**Issue by yujiangqaq** [listen1/listen1_chrome_extension#471]
我的github账户出了点问题，fork这个仓库会报错，故无法使用拉取，只能以这种方式提交pull requests。
麻烦具有这个仓库读写权限的人审核并手动添加一下

[zh-TC.zip](https://github.com/listen1/listen1_chrome_extension/files/5939192/zh-TC.zip)

**Comment by listen1** [comment]
好的，我添加一下。感谢辛苦的付出
