### ISSUE TITLE
QQ音乐部分歌曲无法播放

### ISSUE THREAD

**Issue by LoliWolf** [listen1/listen1_chrome_extension#474]
夢のような
比如这首，一直不能放

**Comment by listen1** [comment]
好的，请先确认一下安装版本号和系统代理设置。刚才试了一下似乎是能够播放的。

**Comment by LoliWolf** [comment]
试了一下，是有会员的都不能放..

**Comment by listen1** [comment]
抱歉，Listen1是通过网站公开接口访问音乐资源的软件，不能播放本身版权受限或受平台保护的歌曲。

**Comment by jackhe16** [comment]
这种场景，貌似会一直重试调用接口，频率很高 。(chrome-extension)版

**Comment by listen1** [comment]
新版可能对受限访问歌曲的自动跳过功能上有些问题，会尽快修复
