### ISSUE TITLE
歌曲播放完成后，无法播放下一首歌曲，需多次点击播放键方可继续播放

### ISSUE THREAD

**Issue by yfShy** [listen1/listen1_chrome_extension#483]
bug: RT.
版本：2.18.0
复现步骤：
如下面视频：
视频（1-5）S: 当前正在播放的歌曲完成后，下一曲
视频（7）S：**出现如题所示问题。点击多次播放键才可以播放歌曲**
视频（16）S：**出现切换至下一首歌曲时 上一首歌曲仍然在播放问题**
视频（30）S：**出现多个能播放的歌曲被跳过，直接播放了《雅俗共赏》问题**

https://user-images.githubusercontent.com/35094951/109452355-875c9800-7a8a-11eb-994d-3ac31f14138b.mp4

**Comment by Dumeng** [comment]
uh, 视频播放不出来。2.19重构了部分代码，可以看看是否有所改善

**Comment by yfShy** [comment]
视频无法播放很抱歉o(╯□╰)o， 我上传到了wb可以看一下。
[2.18.0Bug视频链接](https://weibo.com/tv/show/1034:4610327187488795?from=old_pc_videoshow)

插件更新至2.19.0后，问题仍然存在，
![listen1](https://user-images.githubusercontent.com/35094951/109615707-383c6300-7b6f-11eb-91c6-bac328e53c98.png)

**Comment by listen1** [comment]
修改了播放功能的部分相关代码，能否在V2.20中测试一下是否修复，谢谢

**Comment by yfShy** [comment]
> 修改了播放功能的部分相关代码，能否在V2.20中测试一下是否修复，谢谢

验证了一下，没有问题！作者大大辛苦了(#^.^#)

**Comment by yfShy** [comment]
继而带来的问题就是

**Comment by yfShy** [comment]
继而带来的问题就是这个 Issues提出的问题[https://github.com/listen1/listen1_chrome_extension/issues/548#issue-855555696]
