### ISSUE TITLE
谷歌浏览器无法打开

### ISSUE THREAD

**Issue by TTyb** [listen1/listen1_chrome_extension#486]
可能是gitblog加载错误了，不知道是不是用的是jekyll的问题，已经两天了，显示的页面如下：

GitBlog is loaded incorrectly,It could be Jekyll ,It's been two days since I started chrome extension,the page displays as following:

![20210303](https://user-images.githubusercontent.com/20573808/109741817-cdd80100-7c08-11eb-87bf-c83295a6cd88.png)

**Comment by listen1** [comment]
麻烦能打开开发者工具看一下console中的报错信息吗？还有问一下您安装的插件版本和操作系统版本，谢谢

**Comment by TTyb** [comment]
报错如下：
![image](https://user-images.githubusercontent.com/20573808/109771034-52417880-7c37-11eb-8609-05ccf4036ddc.png)
插件：版本 2.19.0
浏览器：版本 75.0.3770.142（正式版本） （64 位）
操作系统：windows 10

**Comment by Dumeng** [comment]
Optional Chaining语法在Chrome 80以上的版本中实现
Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility

**Comment by listen1** [comment]
@TTyb 暂时可以考虑升级一下chrome到v80以后的版本
考虑到V80版本还是发布不久（2020年2月4日），后期可以考虑把optional chain代码修改为兼容模式。

**Comment by mikelxk** [comment]
我只有在有mediaSession的地方才用了可选链，没想到还是有兼容性问题 😓

**Comment by TTyb** [comment]
@listen1 好的，回头我升级浏览器试试
