### ISSUE TITLE
Github Query param deprecated

### ISSUE THREAD

**Issue by mikelxk** [listen1/listen1_chrome_extension#488]
#467
https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param
We need a quick fix and create a new release since the deprecation take place in 3/5/2021
https://github.com/listen1/listen1_chrome_extension/blob/fd0353fc92764705c36bce2d6e06a849c82085b4/js/github_api.js#L15-L18
https://github.com/listen1/listen1_chrome_extension/blob/fd0353fc92764705c36bce2d6e06a849c82085b4/js/github.js#L7-L23

**Comment by listen1** [comment]
Thanks for your remind. I thought it had been handled but it is not.
