### ISSUE TITLE
[主意] 有人愿意分享自己的歌单给别人吗？

### ISSUE THREAD

**Issue by listen1** [listen1/listen1_chrome_extension#49]
既然有了我的歌单的功能，我在想是否可以有个地方来交流我的歌单？

比如开一个gh-pages页面接受大家歌单的pull request，大家觉得这个主意如何？

**Comment by Lix1993** [comment]
但是不是每个用插件的都用github啊

**Comment by 18dian** [comment]
希望歌单可以互相分享
