### ISSUE TITLE
QQ音乐新限制导致自动寻找源失败

### ISSUE THREAD

**Issue by Dumeng** [listen1/listen1_chrome_extension#492]
![image](https://user-images.githubusercontent.com/5249513/109948876-b3d81480-7d15-11eb-83ce-00346293383f.png)

应在自动寻找源时跳过当前源

**Comment by listen1** [comment]
如果是QQ的VIP会员，可以在Listen1中登录账户解除一些歌曲的限制。插件本身没有绕过官方限制的功能
