### ISSUE TITLE
可以实现导入歌单的记忆播放功能吗？

### ISSUE THREAD

**Issue by xiaozixun** [listen1/listen1_chrome_extension#497]
我导入网易云的歌单后，听此歌单时关闭标签页再开，只会跳到第一首歌，而不是之前听的那首歌。

**Comment by Dumeng** [comment]
这是个bug

**Comment by xiaozixun** [comment]
> 
> 
> 这是个bug

又发现个不知道是不是bug的问题，还是出现在播放导入歌单——如果关闭标签页后再次开启，重新播放之前播放的歌曲时，大概率会无法播放并跳过几首原本可以播放的歌曲。
