### ISSUE TITLE
感觉这个repo主要被请喝茶……

### ISSUE THREAD

**Issue by VinciShark** [listen1/listen1_chrome_extension#5]
有点担心

**Comment by listen1** [comment]
来吧，低调fork一波

**Comment by ss7247** [comment]
fork and star

**Comment by zhanglun** [comment]
低调低调，但是小众软件 已经发推荐了。。。。。

**Comment by VinciShark** [comment]
主要我看异次元的x君发了我就感觉这个要被封……

**Comment by VinciShark** [comment]
要不封装个electron好了，自动升级……传播也比chrome插件方便……话说我有chrome插件的发布账号

**Comment by listen1** [comment]
借问用electron打包后包会很大么？nw.js的打包真的很大。 @VinciShark

**Comment by listen1** [comment]
@zhanglun 不小心就上推荐了，汗

**Comment by listen1** [comment]
https://github.com/electron/electron/issues/2003

@VinciShark 貌似electron也有打包体积过大的问题。这些安装包为了跨平台兼容都内置一个v8引擎，真心大。现在Listen 1的桌面版用PySide+Qt实现的，但打包比较麻烦

**Comment by VinciShark** [comment]
其实……有几个人会在乎这点体积……
但是迭代追更新速度这些electron优势大了

**Comment by listen1** [comment]
估计以后会在插件版里增加检查更新功能：）

**Comment by listen1** [comment]
@VinciShark 考虑了很久觉得你说的没错，而且现在压缩后安装包能到40MB左右。所以我决定先尝试迁移看看，嘿嘿

**Comment by VinciShark** [comment]
@listen1 另外Electron配套的测试框架和调试框架也可以用起来了……比自己搞套技术栈稳多了

**Comment by listen1** [comment]
@VinciShark electron桌面版发布了http://listen1.github.io/listen1/，谢谢你的建议

**Comment by V0idk** [comment]
桌面版不错!

**Comment by Skura23** [comment]
repo主厉害了
