### ISSUE TITLE
有时突然无法播放音乐

### ISSUE THREAD

**Issue by One-In-Dark** [listen1/listen1_chrome_extension#504]
有时单曲循环了很久，突然它就萎了……歌曲变成总时长 00:00，播放键没有任何作用（点击后会变成暂停键，但是不起作用），就像

![图片](https://user-images.githubusercontent.com/61355140/111896639-12abc680-8a56-11eb-9431-6cf1099e82c8.png)

不知道是什么原因呢？

**Comment by One-In-Dark** [comment]
刷新一下，或者重新搜索这首歌然后播放，都可以解决问题。

**Comment by One-In-Dark** [comment]
顺带一提，这是 Firefox 插件版

**Comment by listen1** [comment]
问题应该还存在，会在v2.20中修复，可能与代码中播放失败后的处理逻辑相关。
