### ISSUE TITLE
Refused to execute inline script because it violates the following Content Security Policy directive

### ISSUE THREAD

**Issue by qiansen1386** [listen1/listen1_chrome_extension#506]
19行和61行出现以下bug：

> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem:". Either the 'unsafe-inline' keyword, a hash ('sha256-1txp5IDa2RJP+jXGrosDGOtSQXGck2ebC1g6qu7wz34='), or a nonce ('nonce-...') is required to enable inline execution.

Chrome Version: 89.0.4389.90 (Official Build) (64-bit)
插件版本：2.19.0

我查到好像有一个 workaround 是用 https://csper.io/generator 更新一下本地的 CSP 策略。

或者是手写一个 `script-src 'self' http://xxxx 'unsafe-inline' 'unsafe-eval';` 的 meta tag。

**Comment by qiansen1386** [comment]
不知道是否和 #504 有关

应该 #419 的推进会对这个问题有帮助。

**Comment by listen1** [comment]
感谢反馈。

出错的这两段inline script是为了兼容桌面版而添加的。理论上不执行对插件版没有任何影响。这里利用了csp阻止运行的方式让某些代码只在桌面版运行。具体作用应该是避免module对象导致的某些库不可用的错误。

这种写法确实比较tricky，确实可以改进一下。

手写meta tag因为需要特定域名，针对插件版url可变的情况不知道如何支持。

**Comment by Dumeng** [comment]
https://developer.chrome.com/docs/apps/contentSecurityPolicy/

**Comment by qiansen1386** [comment]
哦哦，我还以为这是网页端出现问题的原因。
