### ISSUE TITLE
咪咕音乐无法播放（如周杰伦的歌曲）

### ISSUE THREAD

**Issue by PlasmolysisMango** [listen1/listen1_chrome_extension#513]
咪咕音乐无法播放（如周杰伦的歌曲）

**Comment by listen1** [comment]
感谢反馈。为了重现问题，能否留下具体无法播放的歌曲名

**Comment by PlasmolysisMango** [comment]
感谢回复，昨天下载的最新版本，周杰伦的大部分歌曲都无法播放，例如《晴天》，而咪咕音乐上周杰伦的歌曲是免费播放的。在咪咕音乐官网测试了一下，只有登录咪咕账号才可以播放，推测是这个原因。

**Comment by listen1** [comment]
好的，可以打开 设置 页面中的 自动切换源 (Beta) 开关，会自动搜索全网能播放的音源。

后期我们会完善平台登录功能。

**Comment by Dumeng** [comment]
随手抓了个包
https://app.c.nf.migu.cn/MIGUM2.0/strategy/listen-url/v2.2?resourceType=2&songId=60054701988&toneFlag=PQ
Header添加一条channel: 0146741

**Comment by RecluseWind** [comment]
Header还需要加上uuid，可以取值1234。

**Comment by listen1** [comment]
暂时解决方案可以点击右上角的用户按钮，使用migu登录后播放，能解决大部分歌曲的播放问题。

如果有好的方案能满足用户需求，我们会更新相关代码。

**Comment by listen1** [comment]
https://github.com/listen1/listen1_chrome_extension/pull/536
