### ISSUE TITLE
能否请教是如何获得api的

### ISSUE THREAD

**Issue by toutouli** [listen1/listen1_chrome_extension#52]
貌似一些api，比如虾米的搜索接口，还有播放接口都说不公开的，请问是如何获得这些api

**Comment by listen1** [comment]
主要看网上一些开发者之前的代码，还有自己抓包分析。

**Comment by wild-flame** [comment]
@toutouli 像歌单之类的有一些是直接抓取的 html 的数据的

**Comment by toutouli** [comment]
@listen1 多谢你的提示，我尝试你的方法，抓包分析了pc客户端的包，获得了上传云盘的api地址，但是数据是加密的。我对加密解密不是很了解，虽然看了你源码里的算法，但是还是无法推导出解密的算法。我原想添加一个一键上传到网易音乐云盘的功能（因为云盘上传功能只能在pc客户端用，而且用起来也有些不方便，如果能直接从别的源一键上传就方便很多），现在卡在这里完全没有进展。

**Comment by listen1** [comment]
@toutouli  https://github.com/darknessomi/musicbox/issues/56

**Comment by nujabse** [comment]
请问有办法获取xiami 每首歌的播放数吗
