### ISSUE TITLE
播放列表删除歌曲后出现多种问题

### ISSUE THREAD

**Issue by magical-l** [listen1/listen1_chrome_extension#528]
在播放列表里，删除当前正在播放歌曲的上一首歌曲后：
1，播放器的进度条不动了，但正在播放的歌曲还在播放。
2，若手动选择播放下一首歌，则正在播放的歌曲依然在播放，同时也开始播放下一首歌，导致同时在播放两首歌。
3，若没有手动切歌，则正在播放的歌曲（第i首）结束后，会跳过下一首歌（第i+1首），直接播放下下首歌（第i+2首）。看起来像是使用序号来定位歌曲，然后列表长度少了1导致跳过了一首。

以上不知是不是由相同原因引起，所以暂时写在一起了。

**Comment by Dumeng** [comment]
是的，有个player中有个index属性，应该是更新播放列表时没有重新计算index

**Comment by listen1** [comment]
related https://github.com/listen1/listen1_desktop/issues/425

**Comment by listen1** [comment]
fixed in https://github.com/listen1/listen1_chrome_extension/pull/533
