### ISSUE TITLE
希望添加登录功能

### ISSUE THREAD

**Issue by Needrom** [listen1/listen1_chrome_extension#53]
找了半天发现没有登陆，然后无奈的切回了网易云，自己的歌单收藏的都是满满的爱哇QAQ。

**Comment by liboyue23** [comment]
I need the same function too!

**Comment by listen1** [comment]
支持导入网易云歌单功能。可以在我的歌单页面，点击打开歌单，输入你的网易云歌单地址，就可以收藏和播放了。
