### ISSUE TITLE
无法取消静音 bug

### ISSUE THREAD

**Issue by Geeyun-JY3** [listen1/listen1_chrome_extension#546]
通过快捷键或点击底部播放栏图标静音后无法再通过相同动作取消静音。Chrome 扩展和 Windows 10 皆可复现。
![gif](https://user-images.githubusercontent.com/49396421/114257655-09c66900-99f4-11eb-8e73-98fc96cd9db9.gif)

**Comment by listen1** [comment]
修复commit：
https://github.com/listen1/listen1_chrome_extension/commit/937bf68139ac7951f7d6ed9add7b4247f0463a31

**Comment by Geeyun-JY3** [comment]
噢抱歉忘记去 commit 历史里先翻翻了
