### ISSUE TITLE
更新火狐以后插件就挂掉了…………

### ISSUE THREAD

**Issue by vxxholic** [listen1/listen1_chrome_extension#56]
火狐中国版47.0.1/Windows 10 专业版 64-bit

在[http://listen1.github.io/listen1](url)重新安装会提示“从此网站下载的附加组件未能安装，因为它看起来已损坏”

**Comment by listen1** [comment]
谢谢你的反馈，我会跟进这个问题

**Comment by listen1** [comment]
firefox 插件下载地址：https://addons.mozilla.org/zh-CN/firefox/addon/listen-1/
