### ISSUE TITLE
Listen1 v3 技术选择讨论

### ISSUE THREAD

**Issue by mikelxk** [listen1/listen1_chrome_extension#564]
前文 #419 #547 
因为#547 的讨论在pr下，
故而新post一个issue来讨论一些技术选择
Feel free to comment under and I will add it above 😃 
| 开发框架 | 优点 | 缺点 |
| --- | --- | --- |
| [AngularJs](https://angularjs.org/) | 现有 | |
| [Vue](https://v3.vuejs.org/) | @Dumeng:`框架和插件在浏览器端进行模板编译和修改都比较好，可以进行零配置开发` | |
| [React](https://reactjs.org/) | @wangbiwang:`三端可以复用大量核心代码` | @Dumeng :`迁移到React会比较困难，因为缺少Directive一类的结构` |
| [Angular](https://angular.io/) | | |
| [Flutter](https://flutter.dev/) | @Dumeng:`当前Flutter 2已经production ready. 可以支持当前的4个频道` | 🐛  |
| etc. | | |

| 网络平台 | 优点 | 缺点 |
| --- | --- | --- |
| 扩展 |现有 | |
| [PWA](https://web.dev/progressive-web-apps/) | | @Dumeng:`PWA不能修改请求头`|

| 开发语言 | 优点 | 缺点 |
| --- | --- | --- |
| JavaScript | 无需编译 | |
| [TypeScript](https://www.typescriptlang.org/) | @wangbiwang:`项目后期迭代肯定是日趋复杂的，如果是基于TS，那后期的维护迭代也能更好的处理` | 需要编译 @Dumeng :`重构到TS也有额外的工作量`|

| 打包工具 | 优点 | 缺点 |
| --- | --- | --- |
| 不打包 | 现有 可直接安装 | 开发不便(缺少hot refresh) |
| [Webpack](https://webpack.js.org/) | |开发编译速度慢 |
| [Vite](https://vitejs.dev/) | 开发编译速度快 | |
| etc. | | |

| 桌面平台 | 优点 | 缺点 |
| --- | --- | --- |
| :electron: [Electron ](https://www.electronjs.org/) | 现有 | 安装包大|
| [PWA](https://web.dev/progressive-web-apps/) | | @Dumeng:`PWA不能修改请求头`|
| etc. | | |

**Comment by mikelxk** [comment]
> 前文 #419 #547
> 因为#547 的讨论在pr下，
> 故而新post一个issue来讨论一些技术选择
> Feel free to comment under and I will add it above 😃
> 
> 开发框架	优点	缺点
> [AngularJs](https://angularjs.org/)	现有	
> [Vue](https://v3.vuejs.org/)	@Dumeng:`框架和插件在浏览器端进行模板编译和修改都比较好，可以进行零配置开发`	
> [React](https://reactjs.org/)	@wangbiwang:`三端可以复用大量核心代码`	@Dumeng :`迁移到React会比较困难，因为缺少Directive一类的结构`
> [Angular](https://angular.io/)		
> [Flutter](https://flutter.dev/)	@Dumeng:`当前Flutter 2已经production ready. 可以支持当前的4个频道`	🐛
> etc.		
> 网络平台	优点	缺点
> 扩展	现有	
> [PWA](https://web.dev/progressive-web-apps/)		
> 开发语言	优点	缺点
> JavaScript	无需编译	
> [TypeScript](https://www.typescriptlang.org/)	@wangbiwang:`项目后期迭代肯定是日趋复杂的，如果是基于TS，那后期的维护迭代也能更好的处理`	需要编译 @Dumeng :`重构到TS也有额外的工作量`
> 打包工具	优点	缺点
> 不打包	现有 可直接安装	开发不便(缺少hot refresh)
> [Webpack](https://webpack.js.org/)		开发编译速度慢
> [Vite](https://vitejs.dev/)	开发编译速度快	
> etc.		
> 桌面平台	优点	缺点
> :electron: [Electron ](https://www.electronjs.org/)	现有	安装包大
> [PWA](https://web.dev/progressive-web-apps/)		
> etc.

**Comment by Dumeng** [comment]
PWA不能修改请求头，当前的接口很多还是需要请求头修改的

**Comment by listen1** [comment]
很好的整理总结。针对Listen1桌面版和插件共用代码的情况，我可能还会尝试几个方案做一些简单的demo验证

**Comment by mikelxk** [comment]
> 很好的整理总结。针对Listen1桌面版和插件共用代码的情况，我可能还会尝试几个方案做一些简单的demo验证

My suggestion on that will be using Monorepo instead of git submodule.

**Comment by Dumeng** [comment]
https://preactjs.com/guide/v10/getting-started

**Comment by duansheli** [comment]
vue 中 可以写 jsx 
vue3 中 可以把属性定义单独写在 ts文件中 
不同的组件引入同一个 ts 文件 也能达到继承复用的效果

**Comment by listen1** [comment]
最近在试验新的框架，已经完成基本功能的80%，会稍后在这个项目建立一个branch放出。以下是大致的技术选择和原因：

1. 使用框架
vue3。vue框架在中文社区有广泛应用，有良好的库支持，并且同类项目大多采用了此框架。虽然react能保持react native版本一部分的代码复用，但是react本身的很多技术需要的技术积累和定制化工作可能稍多。所以选择vue框架作为V3的框架。

2. 是否使用打包工具
目前的版本没有使用打包工具，优点是无需编译，速度快，缺点是代码组织较为艰难，无法使用包的引入这样的代码分割，导致了很多的变量都是全局变量，也不能利用现有的代码分析工具做更深度的检查。所以还是决定V3使用打包工具，但可能在打包桌面版过程中和在实现某些功能（例如后台播放）时有些技术问题需要解决，但总体上打包工具的使用提高了代码质量，收益更大。

3. 其他原因
目前版本因为没有使用redux类似全局状态管理工具，导致了很多时候更改数据不是reactive的，V3会引入Vuex解决问题，Vuex将存储包括播放器状态，设置状态，登录状态等全局状态来简化当前代码中主动刷新的代码。
另一个改变是当前版本是没有路由功能的，实际上自己实现了一套简单的路由显示逻辑，当然代码就比较混乱。V3将引入Vue-router包来解决该问题。同时也顺便支持了浏览器前进后退功能。

基于Vue3的Listen1 V3 代码将在最近推送到本项目的分支。由于之前的功能比较繁杂，第一版可能只会实现最核心的基本功能，主要是把一系列移植的技术问题有一个大的方向的解决方案。后期将逐步把原有功能按照模块迁移到V3分支中。

感谢过去一直关注项目框架升级和提出建议的小伙伴们。期待未来在新的框架下Listen1项目的开发成本更低，开发效率更高。

**Comment by listen1** [comment]
V3 版本的开发分支 https://github.com/listen1/listen1_chrome_extension/tree/next

**Comment by liby** [comment]
刚刚看到这个 issue，虽然技术选型已经结束了，但是我看到这个 issue 下的一些观点，还是不太认同，便想抒发一下自己的观点，事先声明：对事不对人，没有任何引战的意思，如有冒犯，这边先抱歉了。

> 迁移到React会比较困难，因为缺少Directive一类的结构

我不认为这是一个缺点，具体可以参考一下这个问题下的[回答](https://www.zhihu.com/question/314428335)

> Vue和Angular10都比较容易迁移

其实 AngularJS 迁移到 React 也有相关的库可以用，可以达到渐进式迁移的效果，e.g., [react2angular](https://github.com/coatue-oss/react2angular)

> TS 需要编译，重构到TS也有额外的工作量

需要编译这点可能就配置上费点功夫，别的还好；同时我坚定的认为重构到 TS 的收益也是是正相关的，并且类型可以循序渐进的添加，并不需要一蹴而就，一旦类型系统完善，对以后的维护、重构都有很大的帮助

> 如果使用使用React或者Angular10或者TS，就一定需要使用webpack

有跟 Vite 理念相同的 [Snowpack](https://github.com/snowpackjs/snowpack)

> Babel在浏览器端编译不是好的选择

现在很少有人用 Babel 在浏览器端编译 JSX 了，都是 prebuild 了，不过有缺点就是 Babel 加整个 env preset 太大了

**Comment by Dumeng** [comment]
最近有时间重新开始看新的分支，有几个问题不太清楚：
1. 现在既有npm的lockfile也有yarn的lockfile，计划使用哪一个package manager？
2. 现在看到既有js文件，又有ts文件。而且没有看到tsconfig文件。计划是使用哪一个？
3. 现在没有任何的lint插件。

**Comment by listen1** [comment]
> 最近有时间重新开始看新的分支，有几个问题不太清楚：
> 
> 1. 现在既有npm的lockfile也有yarn的lockfile，计划使用哪一个package manager？
> 2. 现在看到既有js文件，又有ts文件。而且没有看到tsconfig文件。计划是使用哪一个？
> 3. 现在没有任何的lint插件。

v3分支还在实验很多功能的移植，可能会有些混乱。
1. 应该会采用yarn
2. ts主要是一个manifest文件，用来定义chrome插件的一些配置的，应该还是会使用js文件为主
3. lint确实还没来得及弄
