### ISSUE TITLE
Firefox: 扩展不可用

### ISSUE THREAD

**Issue by linsui** [listen1/listen1_chrome_extension#571]
刚刚更新到 2.21.1 后发现无法使用。

![sshot-012](https://user-images.githubusercontent.com/36977733/116783620-357ec100-aa7f-11eb-9ce0-64026715ec45.png)

/cc @TNT-c

**Comment by linsui** [comment]
`GithubClient is not defined` 似乎和 https://github.com/listen1/listen1_chrome_extension/issues/570 有关

**Comment by TNT-c** [comment]
我去检查一下

**Comment by TNT-c** [comment]
发现当listen1.html中
` <script type="text/javascript" src="js/github.js"></script>`
时可以使用，但是似乎无法连接github
当` <script type="text/javascript" src="js/github_api.js"></script>`
时不可以使用

**Comment by listen1** [comment]
应该是之前修改支持后台播放遗留的问题，修改了chrome 的manifest.js，没有同步firefox的版本。现在应该已经没有github_api.js文件了，我觉得如果按照chrome插件的manifest.json把文件同步一下应该大概率可以

**Comment by TNT-c** [comment]
上传了新版本，应该解决了没法用和没法连github.com的问题

**Comment by linsui** [comment]
谢谢！

**Comment by listen1** [comment]
方便的话能否提交一下firefox的manifest相关修改
