### ISSUE TITLE
在Microsoft Edge和Google Chrome上画面闪动

### ISSUE THREAD

**Issue by TNT-c** [listen1/listen1_chrome_extension#573]
在微软新版edge上使用深空灰时播放音乐，发现页面下半部分有快速闪动(不是特别明显的忽明忽暗)，用谷歌浏览器也出现同样问题，但在Firefox则没有，请问这是否是浏览器自身原因还是拓展出现了一些小问题

**Comment by listen1** [comment]
下半部分是播放栏吗？最好有个截图或者视频

**Comment by TNT-c** [comment]
录屏出来就看不见了，应该是我显示器问题，打扰了抱歉
