### ISSUE TITLE
listen在Microsoft Edge 外接程序平台上被盗搬

### ISSUE THREAD

**Issue by Hacinsl** [listen1/listen1_chrome_extension#580]
https://microsoftedge.microsoft.com/addons/detail/%E5%9C%A8%E7%BA%BF%E9%9F%B3%E4%B9%90%E7%9B%92/olaohimdpfifjlhlinbpcomealcebinf
在微软的平台上看到的，搜索“音乐”就会出现，最令人不可思议的是居然比listen1的搬运排名靠前
叫做“在线音乐盒”，插件内容似乎没改（甚至里面的名称还是listen1），图标一样，在简介里根本没有提到listen1，甚至连不需要的manifest_firefox.json都没删
评价还不少，但是几乎没有指出这不是原版

**Comment by listen1** [comment]
这可能是seo关键字做的好，搜索的命中就高吧。
Listen1本身是MIT协议开源的似乎也没有特别好的办法，如果内容涉及修改，植入商业性广告，等等社区的小伙伴可以在评论中提醒一下使用者，毕竟我们也有自己社区的小伙伴在维护Listen1在Edge的插件。
