### ISSUE TITLE
实时字幕是否可以支持中文。

### ISSUE THREAD

**Issue by sylva98** [listen1/listen1_chrome_extension#583]
实时字幕是否可以支持中文。

**Comment by listen1** [comment]
请问是指的桌面歌词吗？

**Comment by sylva98** [comment]
是的，桌面歌词。如果歌词可以在状态栏滚动就更妙了。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Listen ***@***.***&gt;; 
发送时间: 2021年5月16日(星期天) 上午8:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [listen1/listen1_chrome_extension] 实时字幕是否可以支持中文。 (#583)





 
请问是指的桌面歌词吗？

**Comment by mikelxk** [comment]
![image](https://user-images.githubusercontent.com/32220948/118527115-8aa31e00-b773-11eb-831a-74dc1c7b1062.png)
你应该指的是chrome自带的实时字幕，那应该是chrome的功能而非listen1

**Comment by sylva98** [comment]
嗯是的，支持中文更妙了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月18日(星期二) 凌晨0:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [listen1/listen1_chrome_extension] 实时字幕是否可以支持中文。 (#583)





 

 你应该指的是chrome自带的实时字幕，那应该是chrome的功能而非listen1

**Comment by mikelxk** [comment]
upstream issue, unrelated to listen1
