### ISSUE TITLE
Clear all playlists while playing causes double play

### ISSUE THREAD

**Issue by mikelxk** [listen1/listen1_chrome_extension#594]
If you clear all playlists while playing song, the song will continue to play and banner will turn to this:
![image](https://user-images.githubusercontent.com/32220948/119647856-5aced700-be53-11eb-8011-88dbb13e1585.png)
play another song will cause two songs playing at the same time.

**Comment by listen1** [comment]
请问是最新的版本么？好像并不能重现。是在特定条件触发bug吗？

**Comment by mikelxk** [comment]
Can't replicate this now. Closes this issue.
