### ISSUE TITLE
Windows免安装版打开时出错

### ISSUE THREAD

**Issue by qxrw** [listen1/listen1_chrome_extension#598]
![1](https://user-images.githubusercontent.com/58656631/120880707-7c238600-c5fe-11eb-82be-f88cc550b480.png)
请问这样的问题怎么解决

**Comment by listen1** [comment]
这种情况应该是初始化时出错了，可以按F12打开开发者模式，看一下console的报错信息吗？谢谢

**Comment by Zergle** [comment]
> 这种情况应该是初始化时出错了，可以按F12打开开发者模式，看一下console的报错信息吗？谢谢

你好，虽然版本不一样，但是我遇到了同样的问题
![image](https://user-images.githubusercontent.com/85275276/127265782-0d9813cf-97e8-4f68-847b-886042f9878e.png)

**Comment by mikelxk** [comment]
https://github.com/listen1/listen1_desktop/issues/500

**Comment by listen1** [comment]
fixed in https://github.com/listen1/listen1_desktop/commit/f3d46d40908af055534fd9c47ced3ca6b5f0f636
