### ISSUE TITLE
GJ，有些歌能搜出来但是时长0，听不了为什么？

### ISSUE THREAD

**Issue by sallyyoo** [listen1/listen1_chrome_extension#6]

**Comment by listen1** [comment]
可能是音乐提供商上的音乐已经下架，以后会完善这部分的出错提示

**Comment by sallyyoo** [comment]
qq音乐的 比如 K RETURN OF KINGS ORIGINAL CHARACTER SONG & SOUNDTRACK CD 这张专辑

**Comment by listen1** [comment]
好的，我已经定位问题了，谢谢你的反馈，正在修复中

**Comment by listen1** [comment]
solved on https://github.com/listen1/listen1_chrome_extension/commit/ec19a8dc884309a228118bfe877b7a7e12bdba1c
现在无法播放的歌曲的标题会灰色显示

**Comment by zunlong1086** [comment]
搜索到的歌曲（如周杰伦的花海），点播放一直在0。
