### ISSUE TITLE
无法搜索QQ音乐内容

### ISSUE THREAD

**Issue by mraandtux** [listen1/listen1_chrome_extension#616]
搜索QQ音乐内容的API地址 i.y.qq.com/s.music/fcgi-bin/search_for_qq_cp （参数已删除）在Firefox开发者工具显示404，导致QQ音乐搜索失效

**Comment by listen1** [comment]
感谢反馈，已经更换了接口

https://github.com/listen1/listen1_chrome_extension/commit/9391466b957c7c538c5205c58a76cc66805a8797
