### ISSUE TITLE
win10桌面安装版的初始化错误（v2.21.6）

### ISSUE THREAD

**Issue by Zergle** [listen1/listen1_chrome_extension#626]
![image](https://user-images.githubusercontent.com/85275276/127265450-7e1947cf-7606-4b6a-bda9-7b0ef5df6757.png)
这是启动界面以及控制台截图

**Comment by mikelxk** [comment]
https://github.com/listen1/listen1_desktop/issues/500
https://github.com/listen1/listen1_chrome_extension/issues/598
似乎enable stop when close 的值是false,导致程序尝试访问chrome.getBackgroundPage,
可以参考第一个issue的fix

**Comment by listen1** [comment]
fixed in https://github.com/listen1/listen1_desktop/commit/f3d46d40908af055534fd9c47ced3ca6b5f0f636
