### ISSUE TITLE
网易云的歌曲现在完全播放不了了

### ISSUE THREAD

**Issue by wy3210953202** [listen1/listen1_chrome_extension#627]
前几天还能听，最近几天不行了，点击网易云的歌曲，只显示页面，不播放音乐

**Comment by Hacinsl** [comment]
我测试了一下可以播放啊

**Comment by zwpaper** [comment]
我也碰到了，有部分歌曲会无法播放，之前还是没问题的，而且重新搜索加入也不行，举个栗子，李荣浩的歌曲“歌谣”，前几天 “歌谣” 专辑里的无法播放，我改到 “嗯” 专辑里的代替了，今天就发现反过来，“嗯” 里的无法播放，“歌谣” 里的可以。

突然想到可以开 Console 看一下，发现 `403 (Forbidden)` 了

**Comment by listen1** [comment]
感谢反馈。能否尝试一下在网易音乐的网页版播放是否有相同的问题？

**Comment by wy3210953202** [comment]
网易云的网页版是可以播放的，但是listen1就不行

**Comment by wy3210953202** [comment]
> 感谢反馈。能否尝试一下在网易音乐的网页版播放是否有相同的问题？

网易云的网页版是可以播放的，但是listen1就不行

**Comment by HydrogenDeuterium** [comment]
试了一下 感觉情况是随机无法播放。 刚才有一首歌前一分钟还能的后一分钟就没了。
似乎有 qq 的歌也出现了类似的问题 但我不能保证是否是个例

**Comment by wy3210953202** [comment]
> 试了一下 感觉情况是随机无法播放。 刚才有一首歌前一分钟还能的后一分钟就没了。
> 似乎有 qq 的歌也出现了类似的问题 但我不能保证是否是个例

**Comment by wy3210953202** [comment]
> 试了一下 感觉情况是随机无法播放。 刚才有一首歌前一分钟还能的后一分钟就没了。
> 似乎有 qq 的歌也出现了类似的问题 但我不能保证是否是个例

是的，今天试了一下突然又能播放了，不知道是什么问题

**Comment by zwpaper** [comment]
现在我不能播放的歌变多了，感觉网易 API 应该有更新，这个 issue 是不是应该开着，看看能否优化一下？

**Comment by wy3210953202** [comment]
希望能优化一下吧

**Comment by pafflee** [comment]
我打开网易云搜索页面是空的，什么也没有，歌单链接输入也没有反应，请问是不是不能搜到网易云的歌了？

**Comment by ChuJian2** [comment]
我开始是直接在Aur安装的，发现有问题后，自己重新构建了最新的，还是这样，找不到原因。

**Comment by mikelxk** [comment]
arch linux默认的electron是16
arch构建时必须指定electron版本为13
https://github.com/listen1/listen1_desktop/issues/608 https://github.com/listen1/listen1_desktop/issues/608
