### ISSUE TITLE
桌面版打开乱码

### ISSUE THREAD

**Issue by LS0002** [listen1/listen1_chrome_extension#628]
![listen1 btt](https://user-images.githubusercontent.com/87508788/127742638-63512fab-0e2a-438e-b7e8-42d6dbcabb81.png)
今天打开的时候突然发现用不了了，删了重装也不行，用另一台电脑发现没问题，但是我的电脑依旧用不了，请问这是什么问题，需要怎么解决

**Comment by HydrogenDeuterium** [comment]
你可能应该去[这里](https://github.com/listen1/listen1_desktop/issues)问。

**Comment by listen1** [comment]
可能是数据存储等问题，可否下载最新版再尝试一下
