### ISSUE TITLE
网易云歌单不能播放

### ISSUE THREAD

**Issue by ctrsgithub** [listen1/listen1_chrome_extension#637]

**Comment by listen1** [comment]
感谢反馈，请补充具体无法播放的歌单，具体无法播放的场景

**Comment by ctrsgithub** [comment]
感谢回复，我刚刚试了一下，又可以使用了。上次不能使用的具体情况是，关于网易云的所有进度条不能加载，但是其他的歌单比如酷狗可以。可能是我这边的网络环境的问题。十分感谢！
