### ISSUE TITLE
9月份起chrome插件版突然报错，报错情况如截图

### ISSUE THREAD

**Issue by luchangharry** [listen1/listen1_chrome_extension#649]
![image](https://user-images.githubusercontent.com/50188136/134275044-b66b1527-571e-413b-b5c1-646949d6a4ee.png)

Uncaught TypeError: Cannot read properties of undefined (reading 'onCommand')

**Comment by KaiyangJi** [comment]
临时办法： chrome.commands && chrome.commands.onCommand.addListener((command) => {
