### ISSUE TITLE
黑色字体的歌曲中部分也会提示“版权原因无法播放”

### ISSUE THREAD

**Issue by clipperL** [listen1/listen1_chrome_extension#65]
刚刚用上，搜了一首“美丽世界的孤儿”；
网易和虾米的歌曲的字体是黑色，QQ音乐的字体是灰色；
灰色字体是无法播放的歌曲，点击提示“版权原因无法播放”，这个很好理解；
可是 黑色字体的歌曲中部分也会提示“版权原因无法播放”。

**Comment by listen1** [comment]
有些歌曲在播放时才会获取版权信息的，但提前尝试所有歌曲的播放状态比较耗时，所以会出现这个问题
