### ISSUE TITLE
代理一直跳错误

### ISSUE THREAD

**Issue by lau0511** [listen1/listen1_chrome_extension#654]
由于人在海外，必须配合回国加速器使用（加速器为插件），每次开了加速器就会一直跳这个错误信息
![image](https://user-images.githubusercontent.com/91549612/135269371-1f3c664f-3ca0-4ae2-9fb8-8c34039a2202.png)

**Comment by Dumeng** [comment]
根据你的截图，找到了可能的插件。其对某些域名的请求有特殊操作。是否能加载其他平台的歌单和音乐？
![image](https://user-images.githubusercontent.com/5249513/135277567-a903391a-cb8b-4204-8b97-47df59b7088a.png)

**Comment by lau0511** [comment]
QQ音乐网易云都是可以加载出来的
刚试了一下，酷我也可以

**Comment by lau0511** [comment]
> 根据你的截图，找到了可能的插件。其对某些域名的请求有特殊操作。是否能加载其他平台的歌单和音乐？ ![image](https://user-images.githubusercontent.com/5249513/135277567-a903391a-cb8b-4204-8b97-47df59b7088a.png)
QQ音乐网易云都是可以加载出来的
刚试了一下，酷我也可以

**Comment by Dumeng** [comment]
如果直接前往对应平台的网页版也出现类似的弹窗的话，建议直接联系该插件的维护者

**Comment by lau0511** [comment]
> 如果直接前往对应平台的网页版也出现类似的弹窗的话，建议直接联系该插件的维护者
不，QQ音乐网易云都没有弹窗
