### ISSUE TITLE
插件上显示的歌和手机上的歌不是同一个版本

### ISSUE THREAD

**Issue by t298** [listen1/listen1_chrome_extension#686]
我的歌单里一直有一首网易云谭维维原唱的“如果有来生”，但是我刚才听到这首歌的时候，在“你从一座叫我的小镇经过”的时候，就变成了一个小男孩唱的了，我原本以为是网易云的歌变了，但我用手机搜索后，手机上还是以前的版本，插件上的歌不对了。

**Comment by t298** [comment]
版本是2.21.6

**Comment by listen1** [comment]
插件因为支持自动切换播放源，可能是原始播放源有问题自动切换到其他平台了。可以在设置页关闭此功能。

**Comment by t298** [comment]
感谢，确实是这个问题
