### ISSUE TITLE
用 GMD 更新页面 UI 

### ISSUE THREAD

**Issue by fuchao2012** [listen1/listen1_chrome_extension#7]
干嘛要去喝茶，多好的，小众的东西

用 google material design 做一个新版 
[https://github.com/fuchao2012/listen1_chrome_extension](https://github.com/fuchao2012/listen1_chrome_extension)

**Comment by listen1** [comment]
可能在未来会分离UI和API代码，到时候欢迎直接贡献UI部分的代码
