### ISSUE TITLE
作者大大 能不能把歌词连上mac上面的小组件啊，还有歌曲没有正在播放的标记

### ISSUE THREAD

**Issue by GakeuiSung** [listen1/listen1_chrome_extension#748]

**Comment by listen1** [comment]
感谢反馈，mac的小组件是最上面的菜单栏么？

**Comment by GakeuiSung** [comment]
是的是的

**Comment by Dumeng** [comment]
![image](https://user-images.githubusercontent.com/5249513/146725870-ab97fc3c-a47f-49a4-b63e-7b0bd3420133.png)
MediaSeesion API

**Comment by mikelxk** [comment]
这是mac自身的实现，和listen1无关
