### ISSUE TITLE
火狐浏览器不支持该插件

### ISSUE THREAD

**Issue by qiangzai201611** [listen1/listen1_chrome_extension#77]
Firefox 版本 52 起，对 Adobe Flash 之外的 NPAPI 插件 的支持会终止， 包括 Java、Microsoft Silverlight 和 Adobe Acrobat 之内的一些插件不会被加载#

**Comment by listen1** [comment]
火狐官方插件地址 https://addons.mozilla.org/zh-CN/firefox/addon/listen-1/

**Comment by listen1** [comment]
firefox 插件下载地址：https://addons.mozilla.org/zh-CN/firefox/addon/listen-1/
