### ISSUE TITLE
导入歌单的时候 提示未能打开输入的歌单地址 是什么意思呀

### ISSUE THREAD

**Issue by bring-down-the-hammer** [listen1/listen1_chrome_extension#785]
RT

**Comment by mikelxk** [comment]
能提供一下歌单网址嘛？

**Comment by bring-down-the-hammer** [comment]
@mikelxk 试了好几个都不行
>  分享先之文创建的歌单「BGM-史诗级大气磅礴震撼心灵」: https://y.music.163.com/m/playlist?id=48466874&userid=343462317&creatorId=31572982 (来自@网易云音乐)
> http://music.163.com/share/sina/direct/13/48466874?userid=343462317&haspic=0
> 分享青丝为谁绾c创建的歌单「我喜欢的音乐」: https://y.music.163.com/m/playlist?id=481135374&userid=343462317&creatorId=343462317 (来自@网易云音乐)

**Comment by mikelxk** [comment]
https://music.163.com/#/playlist?id=48466874&userid=343462317&creatorId=31572982%C2%A0
好像是可以的

**Comment by bring-down-the-hammer** [comment]
我试了一下 那个确实可以 可惜不是我喜欢的歌单😭 是我随手找的

**Comment by mikelxk** [comment]
你得用显示playlist id 然后开头是music.163.com的网址输入
或者实在导入不了的话直接收藏了然后在listen1登录也行

**Comment by bring-down-the-hammer** [comment]
@mikelxk 可以了 🙏🏻
![图片](https://user-images.githubusercontent.com/72541282/151684127-afbd3256-161a-4db7-bf22-b1fc572f9af0.png)
