### ISSUE TITLE
在墙外用不了？

### ISSUE THREAD

**Issue by zhxiaokang** [listen1/listen1_chrome_extension#79]
本人在墙外，发现播放不了网易云里面的任何歌曲
<img width="958" alt="capturfiles_6" src="https://user-images.githubusercontent.com/26897759/28007228-dac0f186-6552-11e7-812c-40a1221b39aa.png">

**Comment by frozentearz** [comment]
我的也是

**Comment by listen1** [comment]
因为音乐授权只在大陆地区，所以大部分中国的在线音乐提供商屏蔽了境外的IP
