### ISSUE TITLE
BUG chrome，加载拓展提示错误。

### ISSUE THREAD

**Issue by Remberance** [listen1/listen1_chrome_extension#792]
错误
Uncaught TypeError: Cannot read properties of undefined (reading 'onCommand')
上下文
_generated_background_page.html
堆叠追踪
js/background.js:195 (匿名函数)

try {
  chrome.webRequest.onBeforeSendHeaders.addListener(
    hack_referer_header,
    {
      urls,
    },
    ['requestHeaders', 'blocking', 'extraHeaders']
  );
} catch (err) {
  // before chrome v72, extraHeader is not supported
  **chrome.webRequest.onBeforeSendHeaders.addListener(**   //这里标黄
    hack_referer_header,

chrome 版本 98.0.4758.82（正式版本） （64 位）

**Comment by mikelxk** [comment]
#783
