### ISSUE TITLE
同步到last.fm？

### ISSUE THREAD

**Issue by Kailasa** [listen1/listen1_chrome_extension#8]
不知道能不能实现last.fm同步呢？

**Comment by martinsol** [comment]
不能同步，Last.fm Scrobbler也检测不到

**Comment by listen1** [comment]
明天将发布最新版支持同步功能，敬请期待

**Comment by Kailasa** [comment]
威武！

**Comment by listen1** [comment]
last.fm 同步功能已经加入，请更新： https://github.com/listen1/listen1_chrome_extension/releases

**Comment by Kailasa** [comment]
刚刚用了，可以同步了，真是太赞，跪谢Orz！！！

**Comment by duchengyao** [comment]
请教一下如何同步last.fm
github授权成功以后会有同步按钮，可last.fm授权以后没有反应
