### ISSUE TITLE
插件打包

### ISSUE THREAD

**Issue by dwqs** [listen1/listen1_chrome_extension#81]
打开 `chrome://extensitions`， 开启开发者模式，chrome 提供了本地的 pack extension, 可以打包成 crx

**Comment by zhangxs1230** [comment]
现在只能安装扩展商店的扩展了，每次打开chrome都要点一下取消，能不能上传上去呢

**Comment by Mydong** [comment]
这种插件很明显是被谷歌禁止的，低调使用吧。

**Comment by listen1** [comment]
谷歌因为安全性考虑取消了本地crx安装的权限，只能用开发者模式安装。
