### ISSUE TITLE
v2.22.0 酷狗仍然无法播放

### ISSUE THREAD

**Issue by sonichy** [listen1/listen1_chrome_extension#812]
修了个寂寞

**Comment by mikelxk** [comment]
我的v2.22.0是可以放的，有可能你需要清空下播放列表
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/32220948/157582012-585bc451-5e47-4cdf-80db-69380ccac22e.png">

**Comment by sonichy** [comment]
清空播放列表，怎么操作？

**Comment by mikelxk** [comment]
<img width="1871" alt="Screenshot 2022-03-09 223203" src="https://user-images.githubusercontent.com/32220948/157583180-d80a2b7c-7648-4016-8e3a-60583853cf66.png">

**Comment by listen1** [comment]
你好，在v2.24.0版本中修复了该功能，请更新，谢谢你的反馈
