### ISSUE TITLE
做了一点点美化

### ISSUE THREAD

**Issue by ConstLhq** [listen1/listen1_chrome_extension#82]
做了一点点美化，详见[README](https://github.com/ConstLhq/listen1_chrome_extension)

![预览1](http://pasteupload.com/images/2017/07/13/Screenshotfrom2017-07-1316-49-04.png)
![预览2](http://pasteupload.com/images/2017/07/13/Screenshotfrom2017-07-1316-48-16.png)

**Comment by ArwenHuang** [comment]
非常感谢作者！这个插件实在是太好用了！省去了听歌找来找去的麻烦，真是谢谢！！！
