### ISSUE TITLE
总是会触发IDM的下载弹窗

### ISSUE THREAD

**Issue by zhangchee7** [listen1/listen1_chrome_extension#883]
有时是在暂停的时候，有时是在播放、切歌的时候

**Comment by sharkmao1106** [comment]
> 有时是在暂停的时候，有时是在播放、切歌的时候

说实话这个IDM下载弹窗是你的问题。
Listen1播放音乐的时候，IDM检测到了文件，就触发了弹窗。
你可以在使用Listen1的时候手动禁用IDM的浏览器扩展就行。

**Comment by MC-dusk** [comment]
我倒希望能主动加入下载按钮，现在每次得抓包才能调用IDM下载

**Comment by jp1017** [comment]
> 我倒希望能主动加入下载按钮，现在每次得抓包才能调用IDM下载

是啊，怎么不触发呢，奇怪，尴尬
