### ISSUE TITLE
qq搜索问题及解决办法（伪），b站搜索歌单问题

### ISSUE THREAD

**Issue by Grsjuoe** [listen1/listen1_chrome_extension#897]
所有音乐搜索报错就是qq搜索的报错，
![image](https://user-images.githubusercontent.com/87079803/183079898-f6033183-f7c6-4f9a-85ca-4638d28bc5a3.png)
据说要登录，那就登录，我登了QQ
![image](https://user-images.githubusercontent.com/87079803/183080065-99825bc9-6e2a-4fbd-b5b3-f7bfe100bf09.png)
然后
![image](https://user-images.githubusercontent.com/87079803/183080222-fe0a60b4-a477-475b-94c0-9483dfa2d091.png)
点进我歌单，里面歌是可以放的
虽然不理解为啥能放我歌单却不能搜……但是迂回也算能听吧。

还有个问题就是b站的搜索，单曲是可以听的，如果搜歌单，点进去会一直转，甚至不知道到底是不是歌单
![image](https://user-images.githubusercontent.com/87079803/183081373-50254f4a-5d46-437a-887d-34437549ddc6.png)

**Comment by Grsjuoe** [comment]
又看了一下，歌单其实还是单曲（视频），搜的结果是一样的，如果阿b没有歌单的话其实禁掉也可以

**Comment by Grsjuoe** [comment]
登录q音后，可以听q音自己的歌单里的歌，也可以把在其中把歌添加到listen1建立的歌单里，就可以听了

**Comment by bwxz** [comment]
QQ这是想干啥啊？

**Comment by listen1** [comment]
感谢反馈，B站的歌单搜索确实因为时间仓促就没做，所以还是搜索单曲的功能。（B站好像没歌单？可能到时候改一下返回空？）

QQ搜索的问题正在解决，之前好像有段时间是API时好时坏，现在可能要考虑彻底换个API。

**Comment by listen1** [comment]
感谢反馈，已经在v2.25.0中解决了该问题
