### ISSUE TITLE
QQ音乐无法播放

### ISSUE THREAD

**Issue by huangzhongxin** [listen1/listen1_chrome_extension#90]
资源的地址改了

**Comment by purplest** [comment]
+1

**Comment by Blade6** [comment]
@listen1 QQ音乐无法播放了，求更新。

**Comment by Chigogo** [comment]
桌面版 QQ音乐无法播放 +1

**Comment by huangzhongxin** [comment]
手动将  `js/provider/qq.js` 中的 `qq_bootstrap_track` 函数中的 `http://cc.stream.qqmusic.qq.com` 改为 `http://dl.stream.qqmusic.qq.com`  就可以了

**Comment by listen1** [comment]
chrome插件版已经更新，谢谢大家的反馈，接下来会重新打包桌面版
