### ISSUE TITLE
QQ音乐无法播放

### ISSUE THREAD

**Issue by snowWave666** [listen1/listen1_chrome_extension#92]
QQ音乐所有资源无法播放

**Comment by ZHENFENG13** [comment]
手动将 js/provider/qq.js 中的 qq_bootstrap_track 函数中的 http://cc.stream.qqmusic.qq.com 改为 http://dl.stream.qqmusic.qq.com 就可以了

**Comment by listen1** [comment]
非常感谢 @ZHENFENG13 的回复，已经将修改提交到代码库
