### ISSUE TITLE
歌单内无法搜索...

### ISSUE THREAD

**Issue by murasaki44** [listen1/listen1_chrome_extension#921]
如题,歌单内无法搜索[https://i.postimg.cc/nhwTYTm4/image.png](url) 从2.23开始不知为什么有了这个问题，输入关键字后无响应，输入字母的话会响应但是只要是包含该字母的都会显示..求作者大人能解决，感谢

**Comment by Grsjuoe** [comment]
我也有这个问题。。

**Comment by murasaki44** [comment]
谢谢作者们的努力 为大家解决了问题 非常感谢！
