### ISSUE TITLE
歌单内搜索问题、b站视频分p问题

### ISSUE THREAD

**Issue by Grsjuoe** [listen1/listen1_chrome_extension#929]
1. listen1自建歌单，含有b站音乐的歌单输入汉字后无响应，输入字母可以响应。
2. b站视频有分p的话：
   无法识别分p，只能播放第一首；
   全站搜索（不是歌单内搜索）也只能识别整个多p视频的总标题，分p的标题匹配不到；

期望作者大大早日解决，辛苦了

**Comment by mikelxk** [comment]
Closed via #975
