### ISSUE TITLE
【重要】listen1 edge发布渠道或因DMCA关闭，寻求帮助！

### ISSUE THREAD

**Issue by dhxh** [listen1/listen1_chrome_extension#938]
有个坏消息和大家分享，今天我收到了网易云音乐的DMCA，因此listen1 在edge临时下架了。   在此寻求援助。如果有对这个比较了解如何解决的人，或者你想对这个事情发表看法和建议，可以在issue留言。

Microsoft has received a Content Infringement Complaint (“Complaint”) regarding your product Listen 1. A copy of the Complaint is in the e-mail below for your review. You may be able to preserve your product by temporarily removing it from the store and following the directions below, if applicable.

 

Next Steps:

1.  Remove product access through Dev Center within one business day (see below for instructions). If your product is still available for download after one business day, Microsoft may remove the product without further notice. 

2.   If you want to restore your product, you have two options:

3.   Option 1: Modify Your Product (see below for instructions)

4.  Option 2: Submit a Counter Notice (see below for instructions)

 

 

 

Options For Restoring Your Product

 

 

Option 1:  Product modifications

I.         Remove your product from the store.

II.        Complete the attached Developer Response & Modification form and submit the completed form by replying to this email.

 

III.              Remove the infringing content based on the original complaint and submit the modified product as an update to the unpublished product.

a.       Please note that passing certification DOES NOT guarantee that the original complainant will be satisfied that you have resolved all issues in the content infringement notice.

If the infringing content based on the original complaint is still evident after the product has been modified, the product may be removed from the store again.

b.      If the modification and product updates are insufficient to the complainant, the complainant may submit a second complaint against the same product. This would be treated as a new complaint for purposes of your Developer’s Account status.

c.       Repeat content infringement complaints can result in termination of your Developer Account even after product modification(s).

IV.          If you are unsure about what to remove, you may wish to contact the complaining party directly. The complaining party’s contact information can be found in the Complaint. 

 

 

Option 2:  Submit a counter notice

I.         Remove your product from the Store.

II.        If the complaint involves copyright and/or trademark concerns, you may complete the attached Microsoft Store – Content Infringement Counter Notice Form. Then, submit the completed form to [mktlegal@microsoft.com](mailto:mktlegal@microsoft.com). (This form is compliant with the Digital Millennium Copyright Act (“DMCA”)).

III.        If the complaint involves solely copyright concerns, you may elect instead to submit a legally-compliant Digital Millennium Copyright Act (“DMCA”) counter-notice to [mktlegal@microsoft.com](mailto:mktlegal@microsoft.com).

  

 

Other        

                       

Please note: the following may result in permanent removal of your product and/or termination of your account:

5.    Failure to remove your product from the Microsoft Store in response to this request

6.    Submitting an update for certification without providing a completed Developer Response & Modification form

7.    Republishing your product after submitting a counter notice prior to receiving Microsoft’s permission to republish

8.    Repeat infringement

9.    Breach of the Microsoft Store App Developer Agreement

 

Note:

10.   Microsoft cannot give you legal advice on this issue, and you should consider consulting your own lawyer if you are unsure about how to proceed.

11.   Under certain circumstances, Microsoft may remove your product immediately without providing you an opportunity to remove it.

12.   To keep your Developer Account in good standing, it is recommended that you review all your products and ensure they comply with Microsoft Store policies.

13.   Microsoft’s DMCA policy may be found here: [https://www.microsoft.com/info/cpyrtInfrg.aspx ](https://www.microsoft.com/info/cpyrtInfrg.aspx%20%20)

14.   This email does not waive or modify the terms of your App Developer Agreement or any of Microsoft’s rights or remedies.

 

 

From: DMCA Agent <dmcaagnt@microsoft.com>
Sent: Thursday, September 15, 2022 10:37 PM
To: Microsoft Store Marketplace Legal <wpmlegal@microsoft.com>
Subject: SIR11287560 - DMCA CERT Portal v2/copyright/杭州网易云音乐科技有限公司

 

Step 1: Contact Info

Notice Type: copyright
First Name: zhen
Last name: zhang
Contact Email: [zhangzhen@corp.netease.com](mailto:zhangzhen@corp.netease.com)
Contact Phone: +86571 89852163 25492
Country: China
Step 2 : Information about your Intellectual Property

IP Owner: 杭州网易云音乐科技有限公司
Comments: Dear Sir/Madam, I have already read and understand the guide of filing DMCA Notice. I represent 杭州网易云音乐科技有限公司, which is a China company with company registration code: 91330108MA27XNADXX registered in China. We have discovered the following service circumventing of our technological protection measures, which is developed and owned by our company and applied to effectively control the access to musical works in Netease Cloud Music’s software/websites/APPs. The developers have knowingly procured or offered to others, without our authorization, a method especially decrypted to the circumvention of technological protection measures. This action might have been considered as a violation against copyright law section 1201. Therefore I am requesting to cease/remove/take down this service from your platform until the developer removed all functions in the APP which is in function to circumvention of technological protection measures, and make access to protected musical contents. The above is a brief description of the violations at stake and is not meant to be a complete statement of our company's prejudice, rights and remedies in connection with the subject matter of this email. All such rights and remedies are expressly reserved, including the rights and remedies of our licensors. I have a good faith belief that use of the copyrighted materials described above on the infringing web page is not authorized by the copyright owner, or its agent, or the law. I have taken fair use into consideration. I swear, under penalty of perjury, that the information in this notification is accurate and that I am the copyright owner, or am authorized to act on behalf of the owner, of an exclusive right that is allegedly infringed.
Original URL: http://music.163.com/
Trademark Registration Number:
Trademark Country Used:
Step 3: Where can the infringing material be found?

https://microsoftedge.microsoft.com/addons/detail/listen-1/hneiglcmpeedblkmbndhfbeahcpjojjg
Step 4: Upload supporting files No Attachments included in the submission Step 5: Signature

Accepted Authority to Act: True
Accepted Good faith Statement: True
Accepted 512 Acknowledgement: True
Signature: Zhen Zhang
 

Ref:MSG6065788_YyygGRmuSXwzsPfdZmfL

**Comment by mikelxk** [comment]
@listen1

**Comment by listen1** [comment]
First, don't be panic. :)

Listen1 之前已经经历过Github DMCA，所以，请按照官方要求提交 DMCA Counter Notice等待进一步结果就可以了。

邮件中比较重要的一段：

> If the complaint involves solely copyright concerns, you may elect instead to submit a legally-compliant Digital Millennium Copyright Act (“DMCA”) counter-notice to [[mktlegal@microsoft.com](mailto:mktlegal@microsoft.com)](mailto:mktlegal@microsoft.com).

现在可以做的就是给这个邮箱写Counter Notice。但请不要尝试在得到进一步许可之前自行发布。官方说这可能导致永久删除。

> Republishing your product after submitting a counter notice prior to receiving Microsoft’s permission to republish

编写Counter Notice请参考一下这个： https://github.com/github/dmca/blob/16b55efeeba0fa4fcc2f0fa1dc1d26b2451fc307/2017/2017-12-01-Listen1-CounterNotice.md

如果过程中有一些问题，可以在这个issue留言或者直接给我发信 githublisten1@gmail.com

**Comment by dhxh** [comment]
今天收到微软回复内容如下：
Hello,

Microsoft cannot give you legal advice on this issue, and you should consider consulting your own lawyer if you are unsure about how to proceed. If you are unsure about what to remove, you may wish to contact the complaining party directly. The complaining party’s contact information can be found in the Complaint.

Thank You,

Microsoft Team

大家有什么好的建议

**Comment by listen1** [comment]
> 今天收到微软回复内容如下： Hello,
> 
> Microsoft cannot give you legal advice on this issue, and you should consider consulting your own lawyer if you are unsure about how to proceed. If you are unsure about what to remove, you may wish to contact the complaining party directly. The complaining party’s contact information can be found in the Complaint.
> 
> Thank You,
> 
> Microsoft Team
> 
> 大家有什么好的建议

请问你大概回复了什么内容？

**Comment by dunkeng** [comment]
https://microsoftedge.microsoft.com/addons/detail/%E5%9C%A8%E7%BA%BF%E9%9F%B3%E4%B9%90%E7%9B%92/olaohimdpfifjlhlinbpcomealcebinf
这个是有人偷偷发上去的吗？安全不？安全我就用这个，不安全只能用CHROME那边的了

**Comment by mikelxk** [comment]
> https://microsoftedge.microsoft.com/addons/detail/%E5%9C%A8%E7%BA%BF%E9%9F%B3%E4%B9%90%E7%9B%92/olaohimdpfifjlhlinbpcomealcebinf
> 
> 这个是有人偷偷发上去的吗？安全不？安全我就用这个，不安全只能用CHROME那边的了

不安全#767

**Comment by dhxh** [comment]
listen1 edge商店恢复了，商店链接https://microsoftedge.microsoft.com/addons/detail/bcneiehcbgahghfmgigmblcgkhihehad
