### ISSUE TITLE
QQ音乐源搜歌无法使用

### ISSUE THREAD

**Issue by heavenyu0303** [listen1/listen1_chrome_extension#948]
qq音乐源搜不了歌了，快乐少了一半

**Comment by mikelxk** [comment]
请问是最新版本的listen1嘛？

**Comment by heavenyu0303** [comment]
用的不是最新版的，我用的还是叫listen1的，最新版已经叫在线音乐盒了，换成最新版的发现就好了，感谢你




山止川行
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "listen1/listen1_chrome_extension"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月26日(星期一) 下午4:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [listen1/listen1_chrome_extension] QQ音乐源搜歌无法使用 (Issue #948)





 
请问是最新版本的listen1嘛？

**Comment by mikelxk** [comment]
在线音乐盒并不是我们维护的项目🤣， #580
你可以在我们的release或者chrome store（edge之前被下架了#938）里直接下载listen1

**Comment by heavenyu0303** [comment]
啊这，release或者chrome store在哪看啊，用edge能看嘛，也是辛苦你们了。意思是listen1只能在chrome浏览器使用了嘛


山止川行
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "listen1/listen1_chrome_extension"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月26日(星期一) 下午5:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [listen1/listen1_chrome_extension] QQ音乐源搜歌无法使用 (Issue #948)





 
在线音乐盒并不是我们维护的项目🤣， #580
 你可以在我们的release或者chrome store（edge之前被下架了#938）里直接下载listen1

**Comment by mikelxk** [comment]
edge也是能用chrome store的 https://chrome.google.com/webstore/detail/listen-1/indecfegkejajpaipjipfkkbedgaodbp
你也可以在release中直接下载zip https://github.com/listen1/listen1_chrome_extension/releases/tag/v2.26.2

**Comment by heavenyu0303** [comment]
那这个listen1就相当于是一个播放器软件了是嘛，不是浏览器的插件了吧




山止川行
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "listen1/listen1_chrome_extension"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月26日(星期一) 下午5:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [listen1/listen1_chrome_extension] QQ音乐源搜歌无法使用 (Issue #948)





 
edge也是能用chrome store的 https://chrome.google.com/webstore/detail/listen-1/indecfegkejajpaipjipfkkbedgaodbp
 你也可以在release中直接下载zip https://github.com/listen1/listen1_chrome_extension/releases/tag/v2.26.2

**Comment by mikelxk** [comment]
上面的这些链接都是浏览器拓展的，
桌面应用在https://github.com/listen1/listen1_desktop

**Comment by heavenyu0303** [comment]
好滴，谢谢您。伟大的程序员




山止川行
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "listen1/listen1_chrome_extension"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月26日(星期一) 下午5:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [listen1/listen1_chrome_extension] QQ音乐源搜歌无法使用 (Issue #948)





 
上面的这些链接都是浏览器拓展的，
 桌面应用在https://github.com/listen1/listen1_desktop
