### ISSUE TITLE
最近也在爬网易云的歌曲遇到点问题想。。。

### ISSUE THREAD

**Issue by yuuki80code** [listen1/listen1_chrome_extension#96]
看了你的源代码对js还不是很懂，我用ids，br，csrf_token 三个参数对/song/enhance/player/url 接口请求，返回参数错误，难道不是这三个参数吗？还有ids是上次请求的哪个id啊求解！

**Comment by listen1** [comment]
请求除了参数，可能还需要注意HTTP Header的构造。
