### ISSUE TITLE
哔哩哔哩无法打开

### ISSUE THREAD

**Issue by ymy2078069948** [listen1/listen1_chrome_extension#964]
下面是问题的录屏：（这是我QQ邮箱，视频打不开联系我2078069948@qq.com，）（下载能看，气死，又发现个GitHub的BUG）

https://user-images.githubusercontent.com/103635982/197143145-0e61b3e5-e52a-4768-8cd0-08f505695708.mp4

详细：1）环境：我用的是win7系统，微软插件安装。
           2）具体：在搜索我在哔站上发布的视频时，发现链接点开后一直无法显示界面（见上面的录屏）
           3）F12：
![F12（1）](https://user-images.githubusercontent.com/103635982/197144666-a294a18b-fecf-4332-b95e-439f1ca62b6c.jpg)
![F12（2）](https://user-images.githubusercontent.com/103635982/197144685-3b800171-461a-4589-932f-30a9494ff996.jpg)
![F12（3）](https://user-images.githubusercontent.com/103635982/197144699-b1e92687-8a52-46f2-9eb5-39769a1e883a.jpg)

最后：感谢大佬们做的程序，大佬们辛苦了！

补充：单曲搜索没问题，我点的是歌单分类（文件太大了，就截个图）
![image](https://user-images.githubusercontent.com/103635982/197148314-4f453ae1-353d-4143-aa12-2ae4c711510a.png)

**Comment by ymy2078069948** [comment]
点错了

**Comment by ymy2078069948** [comment]
评论发不了视频，放上面了

**Comment by listen1** [comment]
已经提交了相关修复：https://github.com/listen1/listen1_chrome_extension/commit/a87be75cf0e04dab2629e7ecfaeedec4a9fb7a8c
