### ISSUE TITLE
能不能关联github或者gmail

### ISSUE THREAD

**Issue by lhwu** [listen1/listen1_chrome_extension#97]
如题，能不能把歌单做个关联。比如关联网易，qq音乐的账号。或者关联gmail。一旦重装系统或者重装了下chrome浏览器，歌单就没了～

**Comment by er567** [comment]
同上，只是存在localstorage的话很容易丢

**Comment by listen1** [comment]
这个比较复杂，还在研究中。如果有比较成熟的解决方案，请留言。现在只能在关于页面中通过备份方式来防止歌单丢失。

**Comment by listen1** [comment]
#118

**Comment by listen1** [comment]
已经在V1.4.0版中加入了github账号登录，支持把歌单同步到gist。
