### ISSUE TITLE
当选择“现代黑”皮肤时开启“显示专辑封面作为背景”会导致播放页歌词只显示一行

### ISSUE THREAD

**Issue by chatseeon** [listen1/listen1_chrome_extension#974]
![屏幕截图 2022-11-08 235611](https://user-images.githubusercontent.com/107085673/200613352-0e4d0269-97e9-4fe5-aff4-4a2e7c768231.jpg)

**Comment by mikelxk** [comment]
仔细看 其实是有的，只是对比度实在太低了
