### ISSUE TITLE
在listen1中连接到last.fm 状态：已连接，在last.fm上可以看到正在Scrobble，但是等歌曲放完了之后并没有记录下来，直接显示了下一首正在播放的歌曲

### ISSUE THREAD

**Issue by asanokiyoe** [listen1/listen1_chrome_extension#986]
如图
![Snipaste_2022-11-23_01-03-51](https://user-images.githubusercontent.com/12674616/203377702-6b78675b-3374-46a0-92d8-26b63d7003fa.png)
![Snipaste_2022-11-23_01-08-36](https://user-images.githubusercontent.com/12674616/203377693-98f8a2cb-b867-4dda-abd1-1dbbceef2efb.png)

**Comment by 1051566182** [comment]
你好，我想问一下这个lastfm不开通订阅版可以记录吗

**Comment by asanokiyoe** [comment]
> 你好，我想问一下这个lastfm不开通订阅版可以记录吗

可以，安卓听歌可以下个Pano Scrobbler，网页版听歌可以在油猴下个插件来记录
